import { registerChapter } from '../../../registry.js';

registerChapter('engels|tl|2|2', {
title:'Health',
summary:[
{heading:'At the doctor\'s',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>Dit hoofdstuk gaat over gezondheid: naar de dokter gaan, ziektes en blessures, en hoe je iemand advies geeft en gerust kunt stellen. Je leert de <b>past continuous</b> (was/were + -ing) om te vertellen wat je aan het doen was toen er iets gebeurde, en hoe je die combineert met de past simple. Ook leer je <b>can</b>, <b>could</b> en <b>should</b> gebruiken om advies te geven. Het hoofdstuk gaat over Singapore, een van de gezondste landen ter wereld.</p></div> <div class=\'call\'>Weetje: de eindopdracht (Task) van dit hoofdstuk is het maken van een strip (comic) over een bezoek aan de dokter, met minstens vijf foto\'s.</div><div class=\'box\'><h4>At the doctor\'s</h4><p>Deze Theme words gebruik je om te praten over een bezoek aan de dokter.</p></div> <div class=\'tblwrap\'><table class=\'tbl\'> <tr><th>Engels</th><th>Nederlands</th></tr> <tr><td>appointment</td><td>afspraak</td></tr> <tr><td>crutches</td><td>krukken</td></tr> <tr><td>dentist</td><td>tandarts</td></tr> <tr><td>(to) examine</td><td>onderzoeken</td></tr> <tr><td>(to) feel worse</td><td>je slechter voelen</td></tr> <tr><td>(to) get better</td><td>beter worden</td></tr> <tr><td>(to) hurt</td><td>pijn doen</td></tr> <tr><td>plaster</td><td>pleister</td></tr> <tr><td>stitches</td><td>hechtingen</td></tr> <tr><td>(to) treat</td><td>behandelen</td></tr> <tr><td>waiting room</td><td>wachtkamer</td></tr> <tr><td>X-ray</td><td>röntgenfoto</td></tr> </table></div> <div class=\'voorbeeld\'><p>I had an appointment with the dentist. She examined my tooth and gave me stitches.</p></div>'},
{heading:'Health conditions',html:'<div class=\'box\'><h4>Health conditions</h4><p>Met deze Theme words vertel je wat er met je aan de hand is.</p></div> <div class=\'tblwrap\'><table class=\'tbl\'> <tr><th>Engels</th><th>Nederlands</th></tr> <tr><td>black eye</td><td>blauw oog</td></tr> <tr><td>headache</td><td>hoofdpijn</td></tr> <tr><td>runny nose</td><td>loopneus</td></tr> <tr><td>sore throat</td><td>zere keel</td></tr> <tr><td>stomach ache</td><td>buikpijn</td></tr> <tr><td>toothache</td><td>kiespijn</td></tr> <tr><td>(to) feel dizzy</td><td>duizelig zijn</td></tr> <tr><td>(to) feel miserable</td><td>je ellendig voelen</td></tr> <tr><td>(to) have a cold</td><td>verkouden zijn</td></tr> <tr><td>(to) have a fever</td><td>koorts hebben</td></tr> <tr><td>(to) have the flu</td><td>griep hebben</td></tr> <tr><td>(to) look pale</td><td>er bleek uitzien</td></tr> </table></div> <div class=\'call warn\'><b>Veelgemaakte fout:</b> je zegt \'I have a headache\', niet \'I have headache\', vergeet het lidwoord \'a\' niet.</div>'},
{heading:'Tips and advice',html:'<div class=\'box\'><h4>Tips and advice</h4><p>Deze Theme words gebruik je om iemand advies te geven of gerust te stellen.</p></div> <div class=\'tblwrap\'><table class=\'tbl\'> <tr><th>Engels</th><th>Nederlands</th></tr> <tr><td>(to) avoid</td><td>vermijden</td></tr> <tr><td>(to) breathe in/out</td><td>in-/uitademen</td></tr> <tr><td>(to) cure</td><td>genezen</td></tr> <tr><td>(to) cut down on</td><td>minderen met</td></tr> <tr><td>(to) hang in there</td><td>volhouden</td></tr> <tr><td>(to) heal</td><td>genezen, helen</td></tr> <tr><td>(to) improve</td><td>verbeteren</td></tr> <tr><td>(to) recover</td><td>herstellen</td></tr> <tr><td>(to) rest</td><td>rusten</td></tr> <tr><td>(to) take a break</td><td>een pauze nemen</td></tr> <tr><td>(to) take it easy</td><td>het rustig aan doen</td></tr> <tr><td>(to) worry</td><td>je zorgen maken</td></tr> </table></div> <div class=\'voorbeeld\'><p>You should rest and take it easy. Don\'t worry, you will recover soon.</p></div>'},
{heading:'Past continuous',html:'<div class=\'box\'><h4>Past continuous: was living</h4><p>Je gebruikt de <b>past continuous</b> voor een activiteit die in het verleden aan de gang was.</p></div> <div class=\'tblwrap\'><table class=\'tbl\'> <tr><th>Onderwerp</th><th>Vorm van \'was/were\'</th><th>Werkwoord + -ing</th></tr> <tr><td>I / he / she / it</td><td>was</td><td>running, cooking, ...</td></tr> <tr><td>you / we / they</td><td>were</td><td>running, cooking, ...</td></tr> </table></div> <div class=\'voorbeeld\'><p>I was running in the park. We were warming up for the game. They were working out in the gym.</p></div> <div class=\'call\'>Je gebruikt de past continuous vaak samen met \'when\' om te vertellen wat er gebeurde tijdens die activiteit: \'I was running in the park when I felt dizzy.\'</div>'},
{heading:'Past continuous en past simple',html:'<div class=\'box\'><h4>She was doing her homework when I called her</h4><p>Als twee gebeurtenissen tegelijk gebeurden, kun je de past continuous en de past simple in één zin gebruiken.</p></div> <div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'> <li>Gebruik de <b>past continuous</b> voor de activiteit die het langst duurde.</li> <li>Gebruik de <b>past simple</b> voor de kortere gebeurtenis die de langere activiteit onderbrak.</li> </ul></div> <div class=\'voorbeeld\'><p>He was swimming in the ocean when he saw a dolphin.<br>They were listening to Spotify until Jimmy\'s phone broke.<br>I bumped my head while I was taking a photo.</p></div> <div class=\'call warn\'><b>Veelgemaakte fout:</b> gebruik niet twee keer de past continuous in zo\'n zin. De korte, plotselinge gebeurtenis staat altijd in de past simple.</div>'},
{heading:'Can, could en should',html:'<div class=\'box\'><h4>Can, could en should</h4><p>Met deze werkwoorden geef je advies of vraag je of iets mogelijk is.</p></div> <div class=\'tblwrap\'><table class=\'tbl\'> <tr><th>Woord</th><th>Gebruik</th><th>Voorbeeld</th></tr> <tr><td>can</td><td>iets is mogelijk / een feit (in het heden)</td><td>You can never leave your phone unlocked.</td></tr> <tr><td>could</td><td>een optie, mildere suggestie</td><td>You could take a hot bath.</td></tr> <tr><td>should</td><td>advies: wat iemand het beste kan doen</td><td>You should exercise to get more energy.</td></tr> </table></div> <div class=\'voorbeeld\'><p>If I were you, I would relax for a couple of days. You must get some rest and not worry too much.</p></div> <div class=\'call warn\'><b>Veelgemaakte fout:</b> je schrijft \'can + not\' als één woord: <i>cannot</i>. Bij \'could\' en \'should\' schrijf je gewoon \'could not\' / \'couldn\'t\' en \'should not\' / \'shouldn\'t\'.</div> <div class=\'call\'>\'Should\' gebruik je om advies te geven, \'could\' om een mogelijkheid te noemen. \'You should see a doctor\' klinkt sterker dan \'You could see a doctor\'.</div>'}
],
terms:[
['appointment','afspraak',0],
['crutches','krukken',0],
['waiting room','wachtkamer',0],
['X-ray','röntgenfoto',0],
['stitches','hechtingen',0],
['headache','hoofdpijn',1],
['sore throat','zere keel',1],
['have a fever','koorts hebben',1],
['feel dizzy','duizelig zijn',1],
['black eye','blauw oog',1],
['(to) rest','rusten',2],
['(to) avoid','vermijden',2],
['(to) recover','herstellen',2],
['(to) take it easy','het rustig aan doen',2],
['was / were','vorm van \'be\' die je gebruikt om de past continuous te maken (was bij I/he/she/it, were bij you/we/they)',3],
['-ing vorm','werkwoordvorm die je in de past continuous achter was/were zet, bijvoorbeeld running, cooking',3],
['when','voegwoord dat je gebruikt om de past continuous (lange activiteit) te koppelen aan de past simple (korte, plotselinge gebeurtenis)',4],
['should','modaal werkwoord dat je gebruikt om advies te geven: wat iemand het beste kan doen',5],
['could','modaal werkwoord dat je gebruikt om een mogelijkheid of milde suggestie te geven',5]
],
cards:[
['appointment','afspraak',0],
['dentist','tandarts',0],
['(to) examine','onderzoeken',0],
['plaster','pleister',0],
['stomach ache','buikpijn',1],
['toothache','kiespijn',1],
['runny nose','loopneus',1],
['(to) have the flu','griep hebben',1],
['(to) improve','verbeteren',2],
['(to) cut down on','minderen met',2],
['(to) heal','genezen, helen',2],
['(to) worry','je zorgen maken',2],
['Maak de past continuous van \'run\' bij \'I\'','I was running',3],
['Maak de past continuous van \'work out\' bij \'they\'','they were working out',3],
['Vul aan: \'He ___ swimming in the ocean when he saw a dolphin.\'','was',4],
['Welke tijd gebruik je voor de korte, onderbrekende gebeurtenis?','de past simple',4],
['Welk woord gebruik je voor sterk advies: \'You ___ see a doctor.\'?','should',5],
['Schrijf \'can not\' als één woord.','cannot',5]
],
quiz:[
['Wat betekent \'appointment\'?',['röntgenfoto','afspraak','krukken','wachtkamer'],1,'\'Appointment\' betekent \'afspraak\'.'],
['Welk woord betekent \'krukken\'?',['crutches','stitches','plaster','X-ray'],0,'\'Crutches\' zijn krukken.'],
['Wat doet een dokter met \'stitches\'?',['een wond hechten','een röntgenfoto maken','bloed prikken','een afspraak maken'],0,'\'Stitches\' zijn hechtingen om een wond te sluiten.'],
['Wat betekent \'sore throat\'?',['hoofdpijn','buikpijn','zere keel','kiespijn'],2,'\'Sore throat\' betekent \'zere keel\'.'],
['Hoe zeg je \'koorts hebben\' in het Engels?',['have a cold','have a fever','feel dizzy','look pale'],1,'\'Have a fever\' betekent \'koorts hebben\'.'],
['Wat betekent \'feel dizzy\'?',['je ellendig voelen','duizelig zijn','verkouden zijn','bleek zien'],1,'\'Feel dizzy\' betekent \'duizelig zijn\'.'],
['Welk woord past bij goed advies geven?',['should','worry','hurt','examine'],0,'\'Should\' gebruik je om advies te geven.'],
['Wat betekent \'(to) cut down on\'?',['genezen','minderen met','rusten','vermijden'],1,'\'(To) cut down on\' betekent \'minderen met\'.'],
['Kies de juiste past continuous: \'I ___ running in the park.\'',['am','were','was','did'],2,'Bij \'I\' gebruik je \'was\' in de past continuous: \'I was running\'.'],
['Kies de juiste past continuous: \'They ___ working out in the gym.\'',['was','were','is','did'],1,'Bij \'they\' gebruik je \'were\': \'They were working out\'.'],
['\'He was swimming in the ocean when he ___ a dolphin.\' Welke tijd?',['was seeing','saw','see','sees'],1,'De korte, plotselinge gebeurtenis staat in de past simple: \'saw\'.'],
['Welke zin combineert past continuous en past simple correct?',['I bumped my head while I taking a photo.','I was bumping my head while I take a photo.','I bumped my head while I was taking a photo.','I was bump my head while I was take a photo.'],2,'De lange activiteit (taking a photo) staat in de past continuous, de korte gebeurtenis (bumped) in de past simple.'],
['Wat is het verschil tussen \'should\' en \'could\'?',['ze betekenen precies hetzelfde','\'should\' is sterker advies, \'could\' is een mildere suggestie','\'could\' is alleen voor de toekomst','\'should\' gebruik je nooit voor advies'],1,'\'Should\' geeft sterker advies dan \'could\', dat meer een optie of suggestie is.'],
['Hoe schrijf je \'can\' + \'not\' als ontkenning?',['can not\'t','cann\'t','cannot','can\'not'],2,'\'Can\' + \'not\' schrijf je als één woord: \'cannot\'.'],
['Welk woord hoort NIET bij \'Tips and advice\'?',['rest','recover','avoid','plaster'],3,'\'Plaster\' (pleister) hoort bij \'At the doctor\'s\', niet bij advies geven.'],
['Wat betekent \'to hang in there\'?',['volhouden','opgeven','je zorgen maken','genezen'],0,'\'To hang in there\' betekent \'volhouden\'.'],
['In welk land speelt de Countries & Cultures-tekst van dit hoofdstuk zich af?',['Malta','Los Angeles','Singapore','Dublin'],2,'Dit hoofdstuk gaat over Singapore, een van de gezondste landen ter wereld.'],
['Wat betekent \'have the flu\'?',['een blauw oog hebben','griep hebben','verkouden zijn','buikpijn hebben'],1,'\'Have the flu\' betekent \'griep hebben\'.']
]
});
