import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|tl|3|5', {
title:'Geluk',
summary:[
{heading:'Geluk zit in een klein...',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>In dit thema ga je aan de slag met verschillende bronnen over geluk: geluksymbolen, filosofen die nadenken over geluk, en onderzoek van Unicef. Je leert een betoog schrijven, een creatieve tekst met beeldspraak schrijven en een vlog maken.</p></div><div class=\'box\'><h4>Wat is geluk?</h4><p>Als je gelukkig bent, dan ben je tevreden met hoe het gaat. Je hebt geen zorgen, er zijn geen problemen en alles gaat zoals jij dat wilt. Soms kun je gelukkig worden van kleine dingen.</p></div><div class=\'term\'><b>Geluk</b><span>1) gunstige gebeurtenis, bijvoorbeeld: \'Het was een geluk bij een ongeluk dat vrienden ons zagen toen we met pech langs de weg stonden.\' (synoniemen: bof, mazzel), 2) gevoel van grote blijheid en harmonie, bijvoorbeeld: \'Het verliefde stelletje straalde van geluk.\'</span></div><div class=\'call\'>In het woord \'geluk\' herken je het werkwoord \'lukken\': als iets lukt, geeft dat vaak een gevoel van geluk.</div>'},
{heading:'Op zoek naar geluk',html:'<div class=\'box\'><h4>Beroemde geluksymbolen</h4><p>Wereldwijd bestaan er in verschillende culturen symbolen waarvan men gelooft dat ze geluk brengen.</p><ul class=\'lst\'><li>Het <b>klavertjevier</b> is een van de bekendste geluksymbolen uit de westerse wereld en is ontstaan in Ierland. Slechts een op de 10.000 klaverplanten heeft een klavertje met vier blaadjes. Elk van de vier blaadjes staat voor iets anders: hoop, liefde, geluk en geloof.</li><li>Het getal <b>7</b> is een bijzonder getal en wordt vaak als geluksgetal gezien. In westerse culturen heeft de 7 een bijzondere waarde, omdat in de Bijbel staat dat God de wereld in 7 dagen heeft geschapen.</li><li><b>Sinaasappels</b> zijn een symbool van geluk in Aziatische culturen. Ze staan voor welvaart en rijkdom, omdat ze de kleur van goud en de vorm van munten hebben.</li></ul></div><div class=\'box\'><h4>Wat is geluk volgens filosofen?</h4><p>Filosofen denken al eeuwenlang na over de vraag wat geluk is. De filosoof <b>Slavoj Žižek</b> stelt dat werkelijk gelukkig zijn een kwestie van meningen is en niet een kwestie van waarheid: je wordt gelukkig door middel van consumptie. In de mens overheerst echter het gevoel van ontevredenheid, omdat we in werkelijkheid niet weten wat we willen. Iedereen gelooft dat wanneer hij iets bereikt (iets kunnen kopen, iets presteren et cetera), hij gelukkig zal zijn, terwijl we in werkelijkheid gewoon weer iets nieuws willen, waardoor mensen voor altijd ontevreden zullen blijven.</p></div><div class=\'box\'><h4>Zo schrijf je een betoog</h4><p>Als je iemand wilt overtuigen van jouw <b>mening</b>, dan kun je een betoog schrijven waarin je je <b>standpunt</b> verduidelijkt met argumenten en uitleg.</p><ul class=\'lst\'><li>In de <b>inleiding</b> geef je kort je mening over het onderwerp. Gebruik daarbij woorden als: <i>ik vind ..., ik denk ..., volgens mij ...</i> om je mening duidelijk te maken.</li><li>In het <b>middenstuk</b> gebruik je voor elk argument één alinea. Noteer in de eerste zin je argument, geef voorbeelden of uitleg, gebruik signaalwoorden voor volgorde (<i>ook, ten tweede, bovendien</i>) en gebruik ook tegenargumenten en weerleggingen om je standpunt te versterken.</li><li>In het <b>slot</b> schrijf je je conclusie: herhaal kort je mening en argumenten met een signaalwoord voor conclusie, zoals <i>dus, kortom, dat betekent</i>.</li><li>Geef je tekst een titel en controleer je tekst op taal- en spelfouten.</li></ul></div><div class=\'call\'>Onderzoek van Unicef laat zien dat Nederland van de 41 meest welvarende landen bovenaan staat als het gaat om onder meer mentale en lichamelijke gezondheid, en sociale en leervaardigheden van kinderen.</div>'},
{heading:'Geluksgevoel',html:'<div class=\'box\'><h4>Creatieve teksten schrijven</h4><p>Fictieschrijvers willen graag dat je kunt wegdromen bij een verhaal. Ze laten je kennismaken met een andere wereld en willen dat je de hoofdpersonen beter leert kennen. Daarom beschrijven ze <b>gevoelens</b> en <b>emoties</b> van personen in hun verhalen. Bijvoorbeeld door te beschrijven wat iemand denkt of hoe de persoon zich voelt. Zoals: <i>Ik kreeg de kriebels toen ik ernaar keek. Wat een enge grote spin! dacht ik.</i></p><p>Met <b>bijvoeglijke naamwoorden</b> kan een schrijver een situatie zo beschrijven dat de lezer zich een beeld kan vormen in zijn hoofd. Bijvoorbeeld: <i>In de donkere kamer zocht Annemieke naar het lichtknopje. Met angstig gezicht en een bezweet voorhoofd tastte ze met haar vingertoppen de ruwe muur af.</i></p><p><b>Beeldspraak</b> is ook een manier om een verhaal sfeer te geven. Beeldspraak is <b>figuurlijk taalgebruik</b>: taal waarmee je iets anders bedoelt dan wat er staat. Op die manier kan een schrijver mooie beeldende zinnen maken.</p></div><div class=\'vergelijk\'><div class=\'vergelijk-kant\'><h4>Zonder beeldspraak</h4><p>De draak keek naar Daan. Daan keek terug naar de rode draak.</p></div><div class=\'vergelijk-vs\'>vs</div><div class=\'vergelijk-kant\'><h4>Met beeldspraak</h4><p>Met ogen als schotels staarde de draak naar Daan. Daan stierf duizend doden en stond te trillen als een juffershondje.</p></div></div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Beschrijf gevoelens en emoties van je hoofdpersonen.</li><li>Gebruik bijvoeglijke naamwoorden om een beeld op te roepen.</li><li>Gebruik beeldspraak (figuurlijk taalgebruik) om je tekst beeldender te maken.</li></ul></div>'},
{heading:'Wat is geluk voor jou?',html:'<div class=\'box\'><h4>Vlogs</h4><p>Een <b>vlog</b> is een persoonlijk verhaal of dagboek in beeld. Vloggers vertellen hun kijkers over hun leven: ze laten zien wat ze hebben meegemaakt of geven hun mening over een onderwerp.</p><p>Een vlog bestaat, net als een tekst, vaak uit een inleiding, middenstuk en slot. In de <b>inleiding</b> enthousiasmeer je je kijkers. In het <b>middenstuk</b> laat je zien wat je wilt delen. In het <b>slot</b> sluit je je vlog af met een conclusie, laatste boodschap of misschien wel een uitdaging. In plaats van te schrijven, neem je bij een vlog de informatie op. De videobeelden knip en plak je daarna met een softwareprogramma in de juiste volgorde. Dat noem je <b>editen</b>.</p></div><div class=\'call sum\'><b>Zo wordt een vlog aantrekkelijk om naar te kijken</b><ul class=\'lst\'><li>Vloggers praten enthousiast en kijken goed in de camera.</li><li>Vloggers introduceren het onderwerp op een creatieve manier.</li><li>Vloggers variëren in de manier van filmen. Het beeld is bijvoorbeeld in close-up, van onderaf of bewegend.</li><li>Vloggers eindigen vaak met een pakkende zin of een oproep.</li></ul></div>'}
],
terms:[
['geluk','1) een gunstige gebeurtenis (bof, mazzel), 2) een gevoel van grote blijheid en harmonie',0],
['klavertjevier','een van de bekendste geluksymbolen uit de westerse wereld, ontstaan in Ierland',1],
['geluksgetal','een getal dat als bijzonder en gelukbrengend wordt gezien, bijvoorbeeld het getal 7',1],
['standpunt','de mening die je in een betoog verdedigt',1],
['betoog','een tekst waarin je een standpunt verduidelijkt met argumenten en uitleg om iemand te overtuigen',1],
['weerlegging','het weerleggen van een tegenargument, waardoor je eigen standpunt sterker wordt',1],
['tegenargument','een argument dat tegen jouw standpunt ingaat',1],
['bijvoeglijk naamwoord','een woord dat een zelfstandig naamwoord nader beschrijft, waardoor de lezer zich een beeld kan vormen',2],
['beeldspraak','figuurlijk taalgebruik waarmee een schrijver een verhaal sfeer geeft',2],
['figuurlijk taalgebruik','taal waarmee je iets anders bedoelt dan wat er letterlijk staat',2],
['vlog','een persoonlijk verhaal of dagboek in beeld',3],
['editen','videobeelden knippen en plakken in de juiste volgorde met een softwareprogramma',3]
],
cards:[
['Wat betekent \'geluk\' als het om een gunstige gebeurtenis gaat?','Een gebeurtenis die toevallig goed uitpakt, zoals bof of mazzel.',0],
['Welk werkwoord herken je in het woord \'geluk\'?','Lukken.',0],
['Waar komt het klavertjevier als geluksymbool oorspronkelijk vandaan?','Uit Ierland.',1],
['Waarom is het getal 7 in westerse culturen een geluksgetal?','Onder andere omdat in de Bijbel staat dat God de wereld in 7 dagen heeft geschapen.',1],
['Wat stelt de filosoof Slavoj Žižek over geluk?','Dat werkelijk gelukkig zijn een kwestie van meningen is, niet van waarheid en dat mensen door consumptie denken gelukkig te worden maar in werkelijkheid altijd ontevreden blijven.',1],
['Wat zet je in de inleiding van een betoog?','Kort je mening over het onderwerp, met woorden als \'ik vind, ik denk, volgens mij\'.',1],
['Wat gebruik je in het middenstuk van een betoog naast argumenten?','Signaalwoorden voor volgorde en tegenargumenten met weerleggingen.',1],
['Wat doe je met bijvoeglijke naamwoorden in een creatieve tekst?','Je beschrijft een situatie zo dat de lezer zich er een beeld bij kan vormen.',2],
['Wat is beeldspraak?','Figuurlijk taalgebruik waarmee een schrijver een verhaal sfeer geeft.',2],
['Uit welke drie delen bestaat een vlog meestal?','Inleiding, middenstuk en slot.',3],
['Wat is editen?','Videobeelden knippen en plakken in de juiste volgorde met een softwareprogramma.',3],
['Noem twee manieren waarop vloggers hun vlog aantrekkelijk maken.','Bijvoorbeeld door enthousiast te praten en goed in de camera te kijken, en door te variëren in de manier van filmen.',3]
],
quiz:[
['Wat betekent geluk als \'gunstige gebeurtenis\'?',['Een gevoel van blijheid','Bof of mazzel','Een spreekwoord','Een filosofische theorie'],1,'Als gunstige gebeurtenis betekent geluk zoiets als bof of mazzel.'],
['Welk werkwoord zit verborgen in het woord \'geluk\'?',['Lukken','Luisteren','Leven','Lachen'],0,'In \'geluk\' herken je het werkwoord \'lukken\'.'],
['Uit welk land komt het klavertjevier als geluksymbool oorspronkelijk?',['Nederland','Ierland','Japan','China'],1,'Het klavertjevier is ontstaan in Ierland.'],
['Waar staan sinaasappels in Aziatische culturen symbolisch voor?',['Verdriet','Welvaart en rijkdom','Pech','Vriendschap'],1,'Sinaasappels staan voor welvaart en rijkdom, vanwege hun kleur (goud) en vorm (munten).'],
['Wat stelt de filosoof Slavoj Žižek over geluk?',['Dat geluk een kwestie van waarheid is','Dat werkelijk gelukkig zijn een kwestie van meningen is, niet van waarheid','Dat consumptie nooit met geluk te maken heeft','Dat mensen altijd tevreden zijn'],1,'Volgens Žižek is werkelijk gelukkig zijn een kwestie van meningen, niet van waarheid.'],
['Wat zet je in de inleiding van een betoog?',['Je conclusie','Kort je mening over het onderwerp','Alleen een vraag','Een opsomming van bronnen'],1,'In de inleiding van een betoog geef je kort je mening over het onderwerp.'],
['Waarvoor gebruik je in het middenstuk van een betoog een tegenargument en een weerlegging?',['Om je eigen standpunt te versterken','Om je mening te verzwakken','Om de tekst korter te maken','Om een conclusie te vermijden'],0,'Een tegenargument met weerlegging maakt je standpunt en argumenten sterker.'],
['Welk signaalwoord past bij de conclusie van een betoog?',['Ten eerste','Kortom','Terwijl','Zoals'],1,'Kortom is een signaalwoord dat past bij de conclusie van een betoog.'],
['Volgens onderzoek van Unicef is Nederland vergeleken met andere welvarende landen:',['Gemiddeld','Bovenaan qua mentale en lichamelijke gezondheid van kinderen','Onderaan de ranglijst','Niet onderzocht'],1,'Unicef-onderzoek laat zien dat Nederland bovenaan staat als het gaat om mentale en lichamelijke gezondheid en sociale en leervaardigheden van kinderen.'],
['Wat is het doel van bijvoeglijke naamwoorden in een creatieve tekst?',['De tekst korter maken','De lezer een beeld laten vormen van een situatie','Spelfouten voorkomen','Een betoog schrijven'],1,'Bijvoeglijke naamwoorden helpen de lezer om zich een beeld te vormen van een situatie.'],
['Wat is beeldspraak?',['Een letterlijke beschrijving','Figuurlijk taalgebruik dat een verhaal sfeer geeft','Een soort signaalwoord','Een tekstdoel'],1,'Beeldspraak is figuurlijk taalgebruik waarmee een schrijver sfeer aan een verhaal geeft.'],
['In de zin \'Met ogen als schotels staarde de draak naar Daan\' is sprake van:',['Een letterlijke beschrijving','Beeldspraak','Een tekstverband','Een tekstdoel'],1,'\'Ogen als schotels\' is een voorbeeld van beeldspraak: figuurlijk taalgebruik.'],
['Wat is een vlog?',['Een geschreven dagboek','Een persoonlijk verhaal of dagboek in beeld','Een betoog','Een moodboard'],1,'Een vlog is een persoonlijk verhaal of dagboek in beeld.'],
['Uit welke drie delen bestaat een vlog meestal?',['Titel, tekst, afbeelding','Inleiding, middenstuk, slot','Mening, argument, conclusie','Onderwerp, doel, publiek'],1,'Net als een tekst bestaat een vlog vaak uit inleiding, middenstuk en slot.'],
['Wat is editen?',['Het schrijven van een script','Videobeelden knippen en plakken in de juiste volgorde','Het filmen zelf','Het uploaden van een video'],1,'Editen is het knippen en plakken van videobeelden in de juiste volgorde met een softwareprogramma.'],
['Wat is geen tip om een vlog aantrekkelijk te maken?',['Enthousiast praten en goed in de camera kijken','Het onderwerp creatief introduceren','Zo veel mogelijk in dezelfde camerahoek filmen zonder variatie','Eindigen met een pakkende zin of oproep'],2,'Vloggers maken hun vlog juist aantrekkelijker door te variëren in de manier van filmen, niet door steeds dezelfde camerahoek te gebruiken.']
]
});
