import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|bbl|1|2', {
title:'Media',
summary:[
{heading:'2.1 Apps',html:'<div class="box"><h4>Mediakennis: begrippen op een rijtje</h4><div class="term"><b>App</b><span>Afkorting van application (applicatie): een computerprogrammaatje dat je op je telefoon zet.</span></div><div class="term"><b>Data</b><span>Gegevens, zoals je contactenlijst, foto\'s en welke sites je bekijkt. Bedrijven moeten hier zorgvuldig mee omgaan; gebruiken ze het verkeerd, dan heet dat misbruik.</span></div><div class="term"><b>Tracking</b><span>Het bijhouden van jouw surfgedrag op internet, bijvoorbeeld via cookies.</span></div><div class="term"><b>Cookies</b><span>Bestandjes die een website op je telefoon of computer zet om informatie over jou te onthouden, bijvoorbeeld je wachtwoord.</span></div><div class="term"><b>Media</b><span>Middelen om informatie over te brengen: kranten, radio, televisie, sociale media, websites, muziek- en videodiensten.</span></div><div class="term" style="margin-bottom:0"><b>Privacy</b><span>Je mag in je privéleven vrij zijn in wie je bent en wat je doet: jij bent de baas over je eigen gegevens.</span></div></div><div class="call warn"><b>Let op:</b> apps kunnen zonder dat je het meteen doorhebt jouw data gebruiken en delen met bedrijven, bijvoorbeeld voor advertenties.</div><div class="call sum"><b>Om te onthouden (2.1)</b><ul class="lst"><li>Een <b>app</b> is een programmaatje op je telefoon; <b>data</b> zijn je gegevens.</li><li><b>Tracking</b> (via <b>cookies</b>) houdt je surfgedrag bij.</li><li><b>Media</b> zijn alle middelen om informatie over te brengen.</li><li><b>Privacy</b> betekent dat jij de baas bent over je eigen gegevens.</li></ul></div>'},
{heading:'2.2 Betrouwbaarheid',html:'<div class="box"><h4>Wanneer is een bericht betrouwbaar?</h4><p>Of een bericht klopt (betrouwbaar is), hangt af van een heleboel dingen. Gebruik deze zes punten als checklist.</p></div><div class="tblwrap" style="margin-top:.6rem"><table class="tbl"><tr><th>Let op</th><th>Waarom</th></tr><tr><td><b>Bron</b></td><td>Een serieuze, professionele site (nieuwssite, krant) is vaak betrouwbaarder dan sociale media.</td></tr><tr><td><b>Inhoud</b></td><td>Lijkt de inhoud te gek om waar te zijn? Zoek dan meer informatie op om het te checken.</td></tr><tr><td><b>Doel</b></td><td>Wil de schrijver iets verkopen? Dan vertelt hij vaak alleen de goede kanten.</td></tr><tr><td><b>Datum</b></td><td>Een oud bericht hoeft niet meer te kloppen.</td></tr><tr><td><b>Taalgebruik</b></td><td>Veel spelfouten kunnen wijzen op een onbetrouwbaar bericht.</td></tr><tr><td><b>Beelden</b></td><td>Plaatjes bij een tekst zijn soms nep en alleen bedoeld om je voor de gek te houden.</td></tr></table></div><div class="call">Geloof dus niet alles wat je online ziet en leest: check bron, inhoud, doel, datum, taalgebruik en beelden.</div><div class="call sum"><b>Om te onthouden (2.2)</b><ul class="lst"><li>De <b>betrouwbaarheid</b> van een bericht check je op bron, inhoud, doel, datum, taalgebruik en beelden.</li><li>Een professionele bron is meestal betrouwbaarder dan een bericht op sociale media.</li><li>Ook plaatjes kunnen nep zijn: beelden zeggen niet automatisch de waarheid.</li></ul></div>'},
{heading:'2.3 Online brainstormen',html:'<div class="box"><h4>Wat is online brainstormen?</h4><p>Online brainstormen is op een snelle en creatieve manier veel ideeën bedenken in een online tool, zoals Google Docs, MindMeister, Miro of Padlet.</p></div><div class="box"><h4>Zo organiseer je een online brainstorm</h4><ol class="num"><li>Kies een duidelijk onderwerp.</li><li>Iedereen bedenkt in vijf minuten zo veel mogelijk ideeën: één idee per digitaal briefje, in stilte.</li><li>Daarna plaatst iedereen elk briefje in een categorie: <b>Now</b>, <b>How</b> of <b>Wow</b>.</li><li>Met de ideeën uit <b>Now</b> en vooral <b>Wow</b> ga je na de brainstorm verder.</li></ol></div><div class="g3"><div class="box"><h4>Now</h4><p>Gewone ideeën die makkelijk uit te voeren zijn. Handig, maar niet bijzonder.</p><p class="dim" style="margin-top:.5rem">Bijv.: meer prullenbakken neerzetten.</p></div><div class="box"><h4>How</h4><p>Originele ideeën die (nog) onmogelijk uit te voeren zijn.</p><p class="dim" style="margin-top:.5rem">Bijv.: een zelfsturende stofzuiger door de kantine.</p></div><div class="box"><h4>Wow</h4><p>Originele ideeën die ook makkelijk uit te voeren zijn: haalbaar én creatief.</p><p class="dim" style="margin-top:.5rem">Bijv.: stickers met een grappige tekst op tafels.</p></div></div><div class="call sum"><b>Om te onthouden (2.3)</b><ul class="lst"><li>Bij <b>online brainstormen</b> bedenk je snel veel ideeën in een online tool.</li><li>Het <b>Now-How-Wow-model</b> verdeelt ideeën in: gewoon en haalbaar (Now), origineel maar onhaalbaar (How), origineel én haalbaar (Wow).</li><li>Je werkt vooral verder met de <b>Now</b>- en <b>Wow</b>-ideeën.</li></ul></div>'},
{heading:'2.4 Een prototype ontwerpen',html:'<div class="g2"><div class="box"><h4>Wat is een prototype?</h4><p>Een <b>prototype</b> is een proefmodel van een product. Zo test je snel en goedkoop je idee, om te leren wat wel en niet werkt voordat je het echte product maakt.</p><p style="margin-top:.6rem">Een prototype kan van alles zijn: een tekening, een model van klei, karton of papier, een stripverhaal...</p></div><div class="box"><h4>Mock-up</h4><p>Een prototype van een <b>app</b> noem je een <b>mock-up</b>: een voorbeeldscherm (of meerdere) dat laat zien hoe de app eruitziet en wat hij kan.</p></div></div><div class="call"><b>Projectsjabloon:</b> een invulvragenlijst die je steeds weer kunt gebruiken bij vergelijkbare projecten, zodat je bij het maken van een mock-up niets vergeet.</div><div class="call sum"><b>Om te onthouden (2.4)</b><ul class="lst"><li>Een <b>prototype</b> is een proefmodel waarmee je een idee goedkoop test.</li><li>Een prototype van een app heet een <b>mock-up</b>: een voorbeeldscherm van de app.</li><li>Een <b>projectsjabloon</b> helpt je om bij het ontwerpen niets te vergeten.</li></ul></div>'},
{heading:'2.5 Pitchen',html:'<div class="box"><h4>Wat is een pitch?</h4><p>Een <b>pitch</b> is een heel korte presentatie, soms van maximaal één minuut, waarin je je publiek probeert over te halen, bijvoorbeeld om jouw product te kopen. Een goede pitch bestaat uit vijf onderdelen.</p></div><div class="g2"><div class="box"><h4>Deel 1: de opening</h4><p>Begin opvallend: met een vraag, of met een gekke of bijzondere situatie die iedereen herkent.</p></div><div class="box"><h4>Laatste deel: de oproep</h4><p>Maak in de laatste stap duidelijk wat je van je publiek wilt, bijvoorbeeld dat ze iets kopen of doen.</p></div></div><div class="call warn"><b>Bronvermelding:</b> vertel altijd waar je informatie vandaan komt. Doe je alsof je alles zelf hebt ontdekt, dan steel je informatie van anderen: dat heet <b>plagiaat</b>.</div><div class="call">Gebruik bij je pitch hulpmiddelen zoals een digitale poster of een PowerPoint: een plaatje bij de opening maakt in één keer duidelijk waar je pitch over gaat.</div><div class="call sum"><b>Om te onthouden (2.5)</b><ul class="lst"><li>Een <b>pitch</b> is een hele korte, overtuigende presentatie van vijf onderdelen.</li><li>Begin met een opvallende opening; eindig met een duidelijke oproep aan je publiek.</li><li>Noem altijd je bronnen: anders is het <b>plagiaat</b>.</li></ul></div>'},
{heading:'2.6 Evalueren en verslag doen',html:'<div class="box"><h4>De ontwerpcyclus</h4><p>Een product ontwerpen doe je in vaste stappen: de <b>ontwerpcyclus</b>.</p><ol class="num"><li>Je onderzoekt wat het probleem is.</li><li>Je brainstormt: je verzamelt ideeën voor het ontwerp van een mock-up.</li><li>Je maakt het ontwerp.</li><li>Je pitcht de mock-up en krijgt feedback.</li><li>Je verwerkt de feedback.</li></ol></div><div class="box"><h4>Een verslag schrijven</h4><p>Een verslag over het ontwerpproces bestaat, net als een gewone tekst, uit drie delen:</p><ul class="lst"><li><b>Inleiding</b>: wat was de opdracht en hoe hebben jullie de taken verdeeld?</li><li><b>Middenstuk</b>: het probleem, het plan, de oplossing en het verloop van het proces (feedback, samenwerking).</li><li><b>Conclusie</b>: je advies om het prototype te verbeteren, met uitleg.</li></ul></div><div class="call">Maak je verslag compleet met: namen, datum, titelpagina, inhoudsopgave, paginanummers, koppen/tussenkoppen en foto\'s van de mock-up.</div><div class="call sum"><b>Om te onthouden (2.6)</b><ul class="lst"><li>De <b>ontwerpcyclus</b> heeft vijf stappen: onderzoeken, brainstormen, ontwerpen, pitchen, feedback verwerken.</li><li>Een verslag over het proces heeft ook een <b>inleiding, middenstuk en conclusie</b>.</li><li>Een compleet verslag heeft een titelpagina, inhoudsopgave, paginanummers en koppen.</li></ul></div>'}
],
terms:[
['app','Afkorting van application: een computerprogrammaatje op je telefoon.',0],
['data','Gegevens van jou, zoals je contactenlijst, foto\'s en bezochte sites.',0],
['tracking','Het bijhouden van jouw surfgedrag op internet.',0],
['cookie','Bestandje dat een website op je apparaat zet om informatie over jou te onthouden.',0],
['media','Middelen om informatie over te brengen, zoals kranten, tv en sociale media.',0],
['privacy','Het recht om zelf de baas te zijn over je eigen gegevens en leven.',0],
['betrouwbaarheid','De mate waarin je een bericht kunt vertrouwen, te checken via bron, inhoud, doel, datum, taalgebruik en beelden.',1],
['bron','De plek waar een bericht vandaan komt.',1],
['online brainstormen','Op een snelle, creatieve manier veel ideeën bedenken in een online tool.',2],
['now-how-wow-model','Model om brainstormideeën in te delen: gewoon (Now), onhaalbaar (How) of haalbaar én origineel (Wow).',2],
['prototype','Een proefmodel van een product, waarmee je een idee test.',3],
['mock-up','Een prototype van een app: een voorbeeldscherm dat laat zien hoe de app eruitziet.',3],
['projectsjabloon','Een invulvragenlijst die je bij vergelijkbare projecten steeds kunt gebruiken.',3],
['pitch','Een hele korte presentatie waarin je je publiek probeert te overtuigen.',4],
['bronvermelding','Aangeven waar je informatie vandaan komt.',4],
['plagiaat','Doen alsof informatie van een ander van jou is.',4],
['ontwerpcyclus','De vaste stappen waarin je een product ontwerpt: onderzoeken, brainstormen, ontwerpen, pitchen, feedback verwerken.',5],
['feedback','Terugkoppeling over wat goed ging en wat beter kan.',5]
],
cards:[
['Wat is het verschil tussen data en tracking?','Data zijn je gegevens; tracking is het bijhouden van je surfgedrag (vaak via cookies).',0],
['Waar zet een cookie informatie neer?','Op je computer of telefoon, om iets over jou te onthouden.',0],
['Welke zes dingen check je voor betrouwbaarheid?','Bron, inhoud, doel, datum, taalgebruik en beelden.',1],
['Waarom is een oud bericht minder betrouwbaar?','De inhoud hoeft niet meer te kloppen als het lang geleden geschreven is.',1],
['Wat is het Now-How-Wow-model?','Een manier om brainstormideeën in te delen: gewoon (Now), onhaalbaar (How), haalbaar én origineel (Wow).',2],
['Met welke ideeën werk je na een brainstorm verder?','Vooral met de Now- en Wow-ideeën.',2],
['Wat is een prototype?','Een proefmodel van een product, om een idee snel en goedkoop te testen.',3],
['Hoe heet een prototype van een app?','Een mock-up.',3],
['Waarvoor gebruik je een projectsjabloon?','Om bij het ontwerpen van een mock-up niets te vergeten.',3],
['Hoe begin je een goede pitch?','Met een opvallende opening: een vraag of een herkenbare, bijzondere situatie.',4],
['Wat moet je aan het eind van een pitch duidelijk maken?','Wat je van je publiek wilt.',4],
['Wat is plagiaat?','Doen alsof informatie van jezelf is, terwijl die van iemand anders komt.',4],
['Wat zijn de vijf stappen van de ontwerpcyclus?','1 Onderzoeken · 2 Brainstormen · 3 Ontwerpen · 4 Pitchen · 5 Feedback verwerken.',5],
['Uit welke drie delen bestaat een verslag over een ontwerpproces?','Inleiding, middenstuk en conclusie.',5]
],
quiz:[
['Wat is een app?',['Een computerprogrammaatje op je telefoon','Een soort cookie','Een vorm van tracking','Een online brainstormtool'],0,'App is de afkorting van application: een programmaatje op je telefoon.'],
['Wat doet een cookie?',['Hij verwijdert je data','Hij onthoudt informatie over jou op een website','Hij blokkeert advertenties','Hij maakt een mock-up'],1,'Een cookie is een bestandje dat een website gebruikt om informatie over jou te onthouden.'],
['Wat betekent privacy?',['Dat je gegevens altijd openbaar zijn','Dat jij de baas bent over je eigen gegevens','Dat je geen apps mag gebruiken','Dat een bericht betrouwbaar is'],1,'Privacy betekent dat je zelf de baas bent over je eigen gegevens en leven.'],
['Welk van deze punten hoort NIET bij de betrouwbaarheidscheck?',['Bron','Datum','Lettertype van de tekst','Doel van de tekst'],2,'De checklist gaat over bron, inhoud, doel, datum, taalgebruik en beelden, niet over het lettertype.'],
['Waarom is de bron belangrijk voor betrouwbaarheid?',['Een professionele bron is vaak betrouwbaarder dan sociale media','De bron zegt niets over betrouwbaarheid','Alleen sociale media zijn betrouwbaar','De bron bepaalt de datum'],0,'Een serieuze, professionele bron is meestal betrouwbaarder dan een bericht op sociale media.'],
['Wat is online brainstormen?',['Alleen op papier ideeën bedenken','Snel en creatief veel ideeën bedenken in een online tool','Een verslag schrijven','Een pitch houden'],1,'Online brainstormen is snel en creatief veel ideeën bedenken in een online omgeving.'],
['Bij welke categorie van het Now-How-Wow-model horen ideeën die haalbaar én origineel zijn?',['Now','How','Wow','Geen van deze'],2,'Wow-ideeën zijn origineel én makkelijk uit te voeren.'],
['Wat is een prototype?',['Het uiteindelijke product','Een proefmodel van een product','Een soort pitch','Een verslag over een ontwerp'],1,'Een prototype is een proefmodel waarmee je een idee test voordat je het echte product maakt.'],
['Hoe heet een prototype van een app?',['Een pitch','Een mock-up','Een cookie','Een projectsjabloon'],1,'Een prototype van een app noem je een mock-up.'],
['Waarvoor gebruik je een projectsjabloon?',['Om een pitch te houden','Om niets te vergeten bij het ontwerpen','Om data te trackenn','Om een verslag te beoordelen'],1,'Een projectsjabloon is een invulvragenlijst zodat je bij het ontwerpen niets vergeet.'],
['Waarmee begin je een goede pitch?',['Met de bronvermelding','Met een opvallende opening','Met de conclusie','Met een verslag'],1,'Een goede pitch begint met een opvallende opening, bijvoorbeeld een vraag.'],
['Wat is plagiaat?',['Een bron correct vermelden','Doen alsof andermans informatie van jou is','Een prototype maken','Feedback geven'],1,'Plagiaat is doen alsof informatie van jezelf is, terwijl die van een ander komt.'],
['Wat is de eerste stap van de ontwerpcyclus?',['Pitchen','Feedback verwerken','Onderzoeken wat het probleem is','Het ontwerp maken'],2,'De ontwerpcyclus begint met onderzoeken wat het probleem is.'],
['Wat gebeurt er in stap 5 van de ontwerpcyclus?',['Je onderzoekt het probleem','Je maakt het ontwerp','Je pitcht de mock-up','Je verwerkt de feedback'],3,'De laatste stap van de ontwerpcyclus is het verwerken van de feedback.'],
['Uit welke drie delen bestaat een verslag over een ontwerpproces?',['Titel, inhoud, bron','Inleiding, middenstuk, conclusie','Pitch, feedback, mock-up','Onderwerp, hoofdgedachte, slot'],1,'Een verslag bestaat uit een inleiding, een middenstuk en een conclusie.'],
['Wat vertel je in de inleiding van zo\'n verslag?',['Je advies over het prototype','Wat de opdracht was en hoe de taken verdeeld waren','De feedback van klasgenoten','De conclusie van het onderzoek'],1,'In de inleiding vertel je wat de opdracht was en hoe jullie de taken hebben verdeeld.']
]
});
