import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|bbl|1|4', {
title:'Taal',
summary:[
{heading:'4.1 Moedertaal',html:'<div class="box"><h4>Wat is moedertaal?</h4><p><b>Moedertaal</b> betekent \'de eerste taal\'. Je krijgt hem mee van je ouders of verzorgers die de taal met je spreken. De allereerste taalontwikkeling begint al in de buik van je moeder: zodra het gehoor van de baby ontwikkeld is, luistert hij al naar het ritme van de taal van zijn moeder. Al een paar uur na de geboorte kunnen baby\'s verschil horen tussen hun moedertaal en een vreemde taal.</p></div><div class="box"><h4>Moedertaal, tweede taal en vreemde taal</h4><div class="term"><b>Moedertaal</b><span>De eerste taal die je leert, meestal van je ouders.</span></div><div class="term"><b>Vreemde taal</b><span>Een taal die je op school leert, maar waarin je jezelf niet altijd in elke situatie kunt redden.</span></div><div class="term" style="margin-bottom:0"><b>Tweetalig</b><span>Twee (of meer) talen even goed kunnen spreken, verstaan, lezen én schrijven.</span></div></div><div class="call">Er bestaan ongeveer 6000 talen op de wereld, verdeeld over minder dan 200 landen. Ongeveer 80% van de wereldbevolking is twee- of meertalig.</div><div class="call sum"><b>Om te onthouden (4.1)</b><ul class="lst"><li><b>Moedertaal</b> is je eerste taal, die je al voor de geboorte begint te herkennen.</li><li>Een <b>vreemde taal</b> beheers je meestal minder goed dan je moedertaal.</li><li><b>Tweetalig</b> ben je pas als je twee talen even goed spreekt, verstaat, leest én schrijft.</li></ul></div>'},
{heading:'4.2 Taal uit de buurt',html:'<div class="box"><h4>Standaardtaal en streektaal</h4><p>De taal die je overal in het land kunt gebruiken en die iedereen begrijpt, noem je de <b>standaardtaal</b>: in Nederland is dat het <b>Standaardnederlands</b>. Niet iedereen spreekt altijd deze standaardtaal: er zijn ongeveer <b>28 streektalen</b> in Nederland.</p></div><div class="box"><h4>Drie officiële streektalen</h4><p>Drie streektalen mogen officieel een eigen taal genoemd worden: het <b>Fries</b>, het <b>Limburgs</b> en het <b>Nedersaksisch</b> (bijvoorbeeld gesproken in Twente). Ook het <b>Brabants</b> is een streektaal, bijvoorbeeld: "\'k zen muug" betekent "ik ben moe".</p></div><div class="call"><b>Ontstaan:</b> streektalen komen uit het verleden. In de middeleeuwen bestond er geen standaardtaal; elke streek had zijn eigen taal. Pas in de zestiende eeuw ontstond de standaardtaal.</div><div class="call sum"><b>Om te onthouden (4.2)</b><ul class="lst"><li>De <b>standaardtaal</b> (Standaardnederlands) is de taal die overal in het land wordt begrepen.</li><li>Nederland heeft ongeveer 28 <b>streektalen</b>, waarvan Fries, Limburgs en Nedersaksisch officieel erkend zijn.</li><li>Streektalen bestaan al sinds de middeleeuwen; de standaardtaal ontstond pas in de zestiende eeuw.</li></ul></div>'},
{heading:'4.3 Bouwstenen',html:'<div class="box"><h4>Waaruit is taal opgebouwd?</h4><p>Taal is opgebouwd uit <b>bouwstenen</b>, net als een legobouwwerk uit losse legostukjes. Bij taal zijn de losse stukjes de <b>letters</b>.</p></div><div class="box"><h4>Van letter tot tekst</h4><ol class="num"><li><b>Letters</b> aan elkaar → een <b>woord</b>.</li><li>Een woord kun je verdelen in <b>lettergrepen</b>: een groepje letters dat samen één klank maakt.</li><li><b>Woorden</b> aan elkaar → een <b>zin</b>.</li><li><b>Zinnen</b> aan elkaar → een <b>tekst</b>.</li></ol></div><div class="call sum"><b>Om te onthouden (4.3)</b><ul class="lst"><li>Taal is opgebouwd uit <b>bouwstenen</b>: letters, lettergrepen, woorden, zinnen en teksten.</li><li>Een <b>lettergreep</b> is een groepje letters dat samen één klank maakt.</li></ul></div>'},
{heading:'4.4 Formeel en informeel',html:'<div class="g2"><div class="box"><h4>Formele taal</h4><p>Beleefd, correct taalgebruik, bijvoorbeeld in een officiële brief.</p><p class="dim" style="margin-top:.5rem">"Geachte mevrouw, wilt u deze brief spoedig beantwoorden?" · "Met vriendelijke groet"</p></div><div class="box"><h4>Informele taal</h4><p>Spreektaal die je gebruikt tussen vrienden, vaak met straattaalwoorden.</p><p class="dim" style="margin-top:.5rem">"Hé Karel, ga je naar de winkel?" · "Spreek je later jongen!"</p></div></div><div class="call warn"><b>Let op:</b> straattaalwoorden zoals "doekoe" (geld), "patta\'s" (schoenen) of "BEF" (beste vriend/vriendin) horen bij informele taal, in een formele brief gebruik je ze niet.</div><div class="call sum"><b>Om te onthouden (4.4)</b><ul class="lst"><li><b>Formele taal</b> is beleefd en correct: gebruik je bijvoorbeeld naar leraren of in officiële brieven.</li><li><b>Informele taal</b> is spreektaal, vaak met straattaal: gebruik je tussen vrienden.</li><li>Kies je taalgebruik op basis van wie je aanspreekt.</li></ul></div>'},
{heading:'4.5 Letterlijk en figuurlijk',html:'<div class="box"><h4>Letterlijk taalgebruik</h4><p>Je zegt precies wat je bedoelt.</p><p class="dim" style="margin-top:.5rem">"De wedstrijd was onwijs spannend."</p></div><div class="box" style="margin-top:1rem"><h4>Figuurlijk taalgebruik</h4><p>Je bedoelt de zin niet letterlijk: het is een <b>uitdrukking</b> met een andere betekenis.</p><p class="dim" style="margin-top:.5rem">"Met je mond vol tanden staan" betekent niet dat je écht met je hele mond vol tanden staat, maar dat je sprakeloos bent en niet weet wat je moet zeggen.</p></div><div class="call">Ook bekende uitdrukkingen zoals "de appel valt niet ver van de boom" of "het ijzer smeden als het heet is" zijn figuurlijk taalgebruik.</div><div class="call sum"><b>Om te onthouden (4.5)</b><ul class="lst"><li><b>Letterlijk</b>: je zegt precies wat je bedoelt.</li><li><b>Figuurlijk</b>: de zin heeft een andere (overdrachtelijke) betekenis dan de losse woorden.</li><li>Uitdrukkingen zijn bijna altijd figuurlijk bedoeld.</li></ul></div>'},
{heading:'4.6 Beeldtaal',html:'<div class="box"><h4>Wat is beeldtaal?</h4><p><b>Beeldtaal</b> bestaat uit tekens die snel laten zien wat er bedoeld wordt, in het verkeer, online, op tv. Deze tekens geven informatie zonder woorden.</p></div><div class="g2"><div class="box"><h4>Verkeerstekens</h4><p>Afspraken in het verkeer worden weergegeven met tekens. Herken je een teken, dan weet je wat je moet doen: zo kun je veilig oversteken of fietsen.</p></div><div class="box"><h4>Emoji\'s</h4><p>"E" in emoji betekent \'afbeelding\', "moji" betekent \'karakter, schriftteken\'. Emoji\'s komen oorspronkelijk uit Japan en worden nu wereldwijd gebruikt.</p></div></div><div class="call">Ook pictogrammen (eenvoudige afbeeldingen in plaats van tekst) zijn beeldtaal: handig, omdat mensen over de hele wereld dezelfde tekens begrijpen.</div><div class="call sum"><b>Om te onthouden (4.6)</b><ul class="lst"><li><b>Beeldtaal</b> zijn tekens die snel informatie overbrengen zonder woorden.</li><li>Verkeerstekens, <b>emoji\'s</b> en pictogrammen zijn voorbeelden van beeldtaal.</li><li>Beeldtaal is wereldwijd bruikbaar: iedereen begrijpt dezelfde tekens.</li></ul></div>'},
{heading:'4.7 Dyslexie',html:'<div class="box"><h4>Wat is dyslexie?</h4><p><b>Dyslexie</b> is een hardnekkig probleem met het aanleren en/of het accuraat en/of vlot toepassen van het lezen en/of spellen op woordniveau.</p></div><div class="box"><h4>Waar kun je moeite mee hebben?</h4><ul class="lst"><li>Het verschil horen tussen klanken, of klanken in de goede volgorde zetten.</li><li>Hardop lezen: dat gaat vaak langzaam, met veel raden.</li><li>Letters die "dansen", of het verwisselen van letters (zoals b en d).</li><li>Spelling en nette schrijfwijze.</li></ul></div><div class="call">Dyslexie heeft ook voordelen: veel kinderen met dyslexie denken creatiever, omdat ze meer met de rechterhelft van de hersenen zouden denken.</div><div class="call sum"><b>Om te onthouden (4.7)</b><ul class="lst"><li><b>Dyslexie</b> is een hardnekkig probleem met lezen en/of spellen op woordniveau.</li><li>Kinderen met dyslexie kunnen moeite hebben met klanken herkennen, hardop lezen en spelling.</li><li>Dyslexie heeft ook voordelen, zoals creatiever denken.</li></ul></div>'}
],
terms:[
['moedertaal','De eerste taal die je leert, meestal van je ouders of verzorgers.',0],
['vreemde taal','Een taal die je (bijvoorbeeld op school) leert, maar niet in elke situatie even goed beheerst.',0],
['tweetalig','Twee talen even goed kunnen spreken, verstaan, lezen én schrijven.',0],
['standaardtaal','De taal die overal in het land wordt gebruikt en begrepen; in Nederland het Standaardnederlands.',1],
['streektaal','Een taal die in een bepaalde regio wordt gesproken, zoals het Fries, Limburgs of Nedersaksisch.',1],
['bouwsteen (van taal)','Een basisonderdeel van taal: letter, lettergreep, woord, zin of tekst.',2],
['lettergreep','Een groepje letters dat samen één klank maakt.',2],
['formele taal','Beleefd, correct taalgebruik, bijvoorbeeld in een officiële brief.',3],
['informele taal','Spreektaal die je gebruikt tussen vrienden, vaak met straattaal.',3],
['letterlijk taalgebruik','Precies zeggen wat je bedoelt.',4],
['figuurlijk taalgebruik','Een zin niet letterlijk bedoelen; een uitdrukking met een andere betekenis.',4],
['uitdrukking','Een vaste combinatie van woorden met een figuurlijke betekenis.',4],
['beeldtaal','Tekens die snel informatie overbrengen zonder woorden, zoals verkeerstekens of emoji\'s.',5],
['pictogram','Een eenvoudige afbeelding die de plaats van tekst inneemt.',5],
['dyslexie','Een hardnekkig probleem met het aanleren en/of toepassen van lezen en/of spellen op woordniveau.',6]
],
cards:[
['Wat is je moedertaal?','De eerste taal die je leert, meestal van je ouders.',0],
['Wanneer ben je volgens de tekst pas echt tweetalig?','Als je twee talen even goed spreekt, verstaat, leest én schrijft.',0],
['Wat is de standaardtaal in Nederland?','Het Standaardnederlands.',1],
['Welke drie streektalen zijn officieel erkend in Nederland?','Fries, Limburgs en Nedersaksisch.',1],
['Waaruit is taal opgebouwd, van klein naar groot?','Letter → lettergreep → woord → zin → tekst.',2],
['Wat is een lettergreep?','Een groepje letters dat samen één klank maakt.',2],
['Wanneer gebruik je formele taal?','Bijvoorbeeld in een officiële brief of tegen iemand die je niet goed kent.',3],
['Wanneer gebruik je informele taal?','Tussen vrienden, vaak met spreektaal of straattaal.',3],
['Wat is het verschil tussen letterlijk en figuurlijk taalgebruik?','Letterlijk: je bedoelt precies wat je zegt. Figuurlijk: de zin heeft een andere betekenis (een uitdrukking).',4],
['Wat betekent "met je mond vol tanden staan"?','Dat je sprakeloos bent en niet weet wat je moet zeggen.',4],
['Wat is beeldtaal?','Tekens die snel informatie geven zonder woorden, zoals verkeerstekens of emoji\'s.',5],
['Waar komt het woord emoji vandaan?','Uit het Japans: "e" betekent afbeelding, "moji" betekent karakter/schriftteken.',5],
['Wat is dyslexie?','Een hardnekkig probleem met het aanleren of toepassen van lezen en/of spellen op woordniveau.',6],
['Noem een voordeel dat mensen met dyslexie vaak hebben.','Ze denken vaak creatiever.',6]
],
quiz:[
['Wat is je moedertaal?',['De taal die je op school leert','De eerste taal die je leert, meestal van je ouders','Een taal die je alleen kunt lezen','Een streektaal'],1,'Moedertaal is de eerste taal die je leert, meestal van je ouders of verzorgers.'],
['Wanneer ben je volgens de tekst pas echt tweetalig?',['Als je een woordje kunt zeggen in een andere taal','Als je twee talen even goed spreekt, verstaat, leest en schrijft','Als je op vakantie gaat naar het buitenland','Als je Engelse les hebt op school'],1,'Je bent pas echt tweetalig als je twee talen allemaal even goed beheerst.'],
['Wat is de standaardtaal in Nederland?',['Het Fries','Het Standaardnederlands','Het Brabants','Het Limburgs'],1,'De standaardtaal in Nederland is het Standaardnederlands.'],
['Welke taal is GEEN officieel erkende streektaal in Nederland?',['Fries','Limburgs','Brabants','Nedersaksisch'],2,'Fries, Limburgs en Nedersaksisch zijn officieel erkend; Brabants is een streektaal maar niet officieel.'],
['Wat is de kleinste bouwsteen van taal?',['De zin','De tekst','De letter','Het woord'],2,'De letter is de kleinste bouwsteen; letters vormen samen woorden, zinnen en teksten.'],
['Wat is een lettergreep?',['Een losse letter','Een groepje letters dat samen één klank maakt','Een hele zin','Een uitdrukking'],1,'Een lettergreep is een groepje letters dat samen één klank vormt.'],
['Welke zin is een voorbeeld van formele taal?',['Hé, ga je mee?','Geachte heer, met vriendelijke groet','Spreek je later!','Yo, alles goed?'],1,'"Geachte heer, met vriendelijke groet" is beleefd en correct: formele taal.'],
['Welke zin is een voorbeeld van informele taal?',['Geachte mevrouw, ik zou u dankbaar zijn','Hé Karel, ga je naar de winkel?','Hoogachtend','Met vriendelijke groet'],1,'"Hé Karel, ga je naar de winkel?" is spreektaal tussen vrienden: informeel.'],
['Wat betekent figuurlijk taalgebruik?',['Je bedoelt precies wat je zegt','De zin heeft een andere betekenis dan de losse woorden','Je gebruikt alleen moeilijke woorden','Je spreekt een streektaal'],1,'Bij figuurlijk taalgebruik is de betekenis anders dan wat de losse woorden letterlijk zeggen.'],
['Wat betekent de uitdrukking "met je mond vol tanden staan"?',['Je hebt tandpijn','Je bent sprakeloos en weet niet wat je moet zeggen','Je hebt net gegeten','Je bent aan het praten'],1,'De uitdrukking betekent dat je sprakeloos bent.'],
['Wat is beeldtaal?',['Een streektaal','Tekens die informatie geven zonder woorden','Een soort dyslexie','Formele schrijftaal'],1,'Beeldtaal bestaat uit tekens (zoals verkeerstekens of emoji\'s) die snel informatie geven, zonder woorden.'],
['Wat betekent "moji" in het woord emoji?',['Afbeelding','Karakter, schriftteken','Gevoel','Telefoon'],1,'"Moji" betekent karakter of schriftteken; "e" betekent afbeelding.'],
['Wat is dyslexie?',['Een probleem met rekenen','Een hardnekkig probleem met lezen en/of spellen op woordniveau','Een streektaal','Een vorm van beeldtaal'],1,'Dyslexie is een hardnekkig probleem met het aanleren of toepassen van lezen en/of spellen.'],
['Wat is een voordeel dat vaak bij dyslexie hoort?',['Sneller kunnen typen zonder spellingscontrole','Creatiever kunnen denken','Beter kunnen rekenen','Meer talen spreken'],1,'Mensen met dyslexie denken volgens de tekst vaak creatiever.']
]
});
