import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|bbl|1|10', {
title:'Bewaren',
summary:[
{heading:'10.1 De 5W+H-vragen',html:'<div class="box"><h4>Waarom de 5W+H-vragen?</h4><p>Soms moet je de belangrijkste informatie uit een tekst opschrijven, bijvoorbeeld voor een <b>samenvatting</b>. Zet dan eerst alle belangrijke informatie op een rijtje met de <b>5W+H-vragen</b>: wie, wat, waar, wanneer, waarom en hoe.</p></div><div class="box" style="margin-top:1rem"><h4>De zes vragen</h4><ul class="lst"><li><b>Wat</b> is er gebeurd?</li><li><b>Wie</b> waren erbij betrokken?</li><li><b>Waar</b> is het gebeurd?</li><li><b>Wanneer</b> gebeurde het?</li><li><b>Waarom</b> gebeurde het?</li><li><b>Hoe</b> gebeurde het?</li></ul></div><div class="call warn"><b>Let op:</b> je kunt niet altijd bij elke tekst of alinea alle vragen beantwoorden. Beantwoord dan de vragen die je wél kunt terugvinden in de tekst.</div><div class="call sum"><b>Om te onthouden (10.1)</b><ul class="lst"><li>De <b>5W+H-vragen</b> zijn: wie, wat, waar, wanneer, waarom, hoe.</li><li>Ze helpen je de belangrijkste informatie uit een tekst te halen, bijvoorbeeld voor een samenvatting.</li></ul></div>'},
{heading:'10.2 Een presentatie geven',html:'<div class="box"><h4>Opbouw van een presentatie</h4><p>Een goede presentatie heeft een <b>inleiding, middenstuk en slot</b>. In de inleiding vertel je waar de presentatie over gaat en waarom je dit onderwerp koos. In het middenstuk vertel je alle informatie. Bij het slot laat je weten dat de presentatie afgelopen is (met een slotzin en je mening) en vraag je of het publiek nog vragen heeft.</p></div><div class="g2" style="margin-top:1rem"><div class="box"><h4>Zo bereid je een presentatie voor</h4><ul class="lst"><li>Bedenk wat je wilt vertellen met de <b>5W+H-vragen</b>.</li><li>Maak een spreekkaartje per 5W+H-vraag, plus één voor de inleiding en één voor het slot, met steekwoorden.</li><li>Zoek afbeeldingen of voorwerpen die je presentatie duidelijker of aantrekkelijker maken.</li><li>Oefen je presentatie, bijvoorbeeld voor je ouders of een klasgenoot.</li></ul></div><div class="box"><h4>Zo geef je een presentatie</h4><ul class="lst"><li>Praat rustig, duidelijk en hard genoeg.</li><li>Kijk zo veel mogelijk naar je publiek, niet te veel op je spreekkaartjes.</li><li>Gebruik je lichaam, handen en gezichtsuitdrukking.</li><li>Vertel bij afbeeldingen of voorwerpen ook iets erover.</li><li>Vraag aan het eind of het publiek nog vragen heeft.</li></ul></div></div><div class="call sum"><b>Om te onthouden (10.2)</b><ul class="lst"><li>Een presentatie heeft een <b>inleiding, middenstuk en slot</b>.</li><li>Bereid voor met spreekkaartjes op basis van de <b>5W+H-vragen</b>.</li><li>Praat rustig en duidelijk, en kijk naar je publiek in plaats van naar je kaartjes.</li></ul></div>'},
{heading:'10.3 Instrueren',html:'<div class="box"><h4>Een mondelinge instructie geven</h4><p>In een instructie vertel je <b>stap voor stap</b> wat iemand moet doen. Let goed op of je luisteraars de instructie begrijpen.</p></div><div class="box" style="margin-top:1rem"><h4>Zo geef je instructie</h4><ul class="lst"><li>Vertel over welk onderwerp je instructie gaat.</li><li>Leg stap voor stap en in een <b>logische volgorde</b> uit wat er moet gebeuren.</li><li>Begin elke stap met een <b>doe-woord</b> (werkwoord): Neem... Loop... Pak...</li><li>Gebruik <b>signaalwoorden voor volgorde</b>: eerst... daarna... vervolgens...</li><li>Spreek rustig en goed verstaanbaar.</li></ul></div><div class="call sum"><b>Om te onthouden (10.3)</b><ul class="lst"><li>Een <b>instructie</b> geef je stap voor stap, in een logische volgorde.</li><li>Gebruik <b>doe-woorden</b> en <b>signaalwoorden voor volgorde</b>.</li><li>Spreek rustig en goed verstaanbaar zodat je luisteraars je kunnen volgen.</li></ul></div>'},
{heading:'10.4 Een korte instructie schrijven',html:'<div class="box"><h4>Een instructie schrijven</h4><p>In een geschreven instructie beschrijf je stap voor stap wat de lezer moet doen.</p></div><div class="box" style="margin-top:1rem"><h4>Zo schrijf je een instructie</h4><ul class="lst"><li>Noteer waarover de instructie gaat.</li><li>Schrijf in <b>eenvoudige zinnen</b> en in een <b>logische volgorde</b> wat er moet gebeuren.</li><li>Begin elke zin met een <b>doe-woord</b>.</li><li>Gebruik <b>volgordewoorden</b>: eerst, daarna, vervolgens.</li><li><b>Nummer</b> de stappen of gebruik opsommingstekens (streepjes/bolletjes).</li><li>Geef je instructie een <b>titel</b>.</li><li>Gebruik <b>afbeeldingen</b> om je instructie duidelijker te maken.</li></ul></div><div class="call sum"><b>Om te onthouden (10.4)</b><ul class="lst"><li>Schrijf een instructie in genummerde, eenvoudige stappen met doe-woorden.</li><li>Gebruik volgordewoorden en een titel; afbeeldingen maken het duidelijker.</li></ul></div>'}
],
terms:[
['5W+H-vragen','Wie, wat, waar, wanneer, waarom en hoe: vragen om de belangrijkste informatie uit een tekst te halen.',0],
['samenvatting','Een korte tekst waarin je de belangrijkste informatie van een langere tekst noteert.',0],
['inleiding (presentatie)','Het begin van een presentatie, waarin je vertelt waar het over gaat.',1],
['middenstuk (presentatie)','Het deel van de presentatie met alle informatie over het onderwerp.',1],
['slot (presentatie)','Het einde van een presentatie, met een slotzin, je mening en ruimte voor vragen.',1],
['spreekkaartje','Een kaartje met steekwoorden om je te helpen tijdens het presenteren.',1],
['instructie','Een tekst of uitleg die stap voor stap vertelt wat iemand moet doen.',2],
['doe-woord','Een werkwoord waarmee je een stap in een instructie begint, zoals "neem" of "pak".',2],
['signaalwoord (volgorde)','Een woord dat de volgorde aangeeft, zoals eerst, daarna of vervolgens.',2]
],
cards:[
['Wat betekenen de letters van de 5W+H-vragen?','Wie, wat, waar, wanneer, waarom en hoe.',0],
['Waarvoor gebruik je de 5W+H-vragen?','Om de belangrijkste informatie uit een tekst te halen, bijvoorbeeld voor een samenvatting.',0],
['Uit welke drie delen bestaat een goede presentatie?','Inleiding, middenstuk en slot.',1],
['Wat doe je in de inleiding van een presentatie?','Vertellen waar de presentatie over gaat en waarom je dit onderwerp koos.',1],
['Waarmee bereid je een presentatie voor?','Met spreekkaartjes op basis van de 5W+H-vragen.',1],
['Waar moet je tijdens een presentatie vooral naar kijken?','Naar je publiek, niet te veel naar je spreekkaartjes.',1],
['Waarmee begin je elke stap van een instructie?','Met een doe-woord (werkwoord).',2],
['Noem drie signaalwoorden voor volgorde.','Eerst, daarna, vervolgens.',2],
['Wat moet je bij een mondelinge instructie extra goed doen?','Rustig en goed verstaanbaar spreken, en checken of je luisteraars het begrijpen.',2],
['Wat hoort er bij een geschreven instructie, naast genummerde stappen?','Een titel en eventueel afbeeldingen.',3]
],
quiz:[
['Wat betekenen de 5W+H-vragen?',['Wie, wat, waar, wanneer, waarom, hoe','Waarom, wat, wie, wanneer, wat, hoeveel','Wie, wat, wanneer, waarom, wie, waar','Waar, wanneer, wat, hoe, wie, wij'],0,'De 5W+H-vragen zijn: wie, wat, waar, wanneer, waarom en hoe.'],
['Waarvoor gebruik je de 5W+H-vragen?',['Om een presentatie te versieren','Om de belangrijkste informatie uit een tekst te halen','Om een tekst langer te maken','Om een instructie te versnellen'],1,'De 5W+H-vragen helpen je om de belangrijkste informatie uit een tekst op een rijtje te zetten.'],
['Uit welke drie delen bestaat een goede presentatie?',['Titel, inhoud, bron','Inleiding, middenstuk, slot','Vraag, antwoord, uitleg','Onderwerp, doel, publiek'],1,'Een presentatie bestaat uit een inleiding, een middenstuk en een slot.'],
['Wat vertel je in de inleiding van een presentatie?',['De belangrijkste informatie in detail','Waar de presentatie over gaat en waarom je dit onderwerp koos','Je conclusie','Of het publiek nog vragen heeft'],1,'In de inleiding vertel je waar je presentatie over gaat en waarom je dit onderwerp hebt gekozen.'],
['Wat gebeurt er in het slot van een presentatie?',['Je begint met het onderwerp','Je geeft alle informatie','Je rondt af en vraagt om vragen van het publiek','Je maakt een spreekkaartje'],2,'In het slot rond je af, geef je je mening en vraag je of het publiek nog vragen heeft.'],
['Waarmee maak je een spreekkaartje?',['Met de hele tekst van je presentatie','Met steekwoorden voor de belangrijkste informatie','Met alleen plaatjes','Met een 5W+H-vraag zonder antwoord'],1,'Een spreekkaartje bevat steekwoorden met de belangrijkste informatie, niet de hele tekst.'],
['Waar moet je tijdens het presenteren vooral naar kijken?',['Naar je spreekkaartjes','Naar het plafond','Naar je publiek','Naar de deur'],2,'Je kijkt zo veel mogelijk naar je publiek en niet te veel op je spreekkaartjes.'],
['Wat is een instructie?',['Een mening over een tekst','Een tekst die stap voor stap vertelt wat je moet doen','Een samenvatting van een verhaal','Een presentatie over jezelf'],1,'Een instructie vertelt stap voor stap wat iemand moet doen.'],
['Waarmee begin je elke stap van een instructie?',['Met een lidwoord','Met een doe-woord','Met een vraagteken','Met een verwijswoord'],1,'Elke stap van een instructie begin je met een doe-woord (werkwoord), zoals "neem" of "pak".'],
['Welk woord is GEEN signaalwoord voor volgorde?',['Eerst','Daarna','Vervolgens','Misschien'],3,'Eerst, daarna en vervolgens geven volgorde aan; "misschien" doet dat niet.'],
['Waar moet je bij een mondelinge instructie extra op letten?',['Op je kleding','Op rustig en verstaanbaar spreken','Op de kleur van je spreekkaartje','Op het aantal toehoorders'],1,'Bij een mondelinge instructie is het belangrijk rustig en goed verstaanbaar te spreken.'],
['Wat hoort bij een goed geschreven instructie?',['Alleen lopende tekst zonder stappen','Genummerde stappen, een titel en eventueel afbeeldingen','Een gedicht als titel','Alleen een tekening zonder tekst'],1,'Een goede instructie heeft genummerde stappen, een titel en kan met afbeeldingen verduidelijkt worden.']
]
});
