import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|bbl|1|12', {
title:'Helden',
summary:[
{heading:'12.1 Vragen stellen: open en gesloten',html:'<div class="box"><h4>Waarom vragen stellen?</h4><p>In een interview stelt de interviewer vragen om aan informatie te komen. Een interviewer kan <b>open</b> of <b>gesloten</b> vragen stellen.</p></div><div class="g2" style="margin-top:1rem"><div class="box"><h4>Gesloten vraag</h4><p>Maar één kort antwoord mogelijk, vaak ja of nee.</p><p class="dim" style="margin-top:.5rem">"Vind je je beroep leuk?" · "Hoe oud ben je?"</p></div><div class="box"><h4>Open vraag</h4><p>Geeft vaak een uitgebreider antwoord. Begint vaak met <b>hoe, waarom</b> of <b>wat</b>.</p><p class="dim" style="margin-top:.5rem">"Hoe wist u wat u moest doen?" · "Waarom zit je op rugby?"</p></div></div><div class="call sum"><b>Om te onthouden (12.1)</b><ul class="lst"><li>Een <b>gesloten vraag</b> geeft een kort antwoord (vaak ja/nee).</li><li>Een <b>open vraag</b> (hoe/waarom/wat) geeft een uitgebreider antwoord.</li></ul></div>'},
{heading:'12.2 Interviewvragen: feiten, meningen en gevoelens',html:'<div class="box"><h4>Drie soorten vragen</h4><p>In interviews worden verschillende soorten vragen gesteld. Een interviewer kan vragen naar:</p></div><div class="g3" style="margin-top:1rem"><div class="box"><h4>Feiten</h4><p class="dim">"Kun je vertellen wat er gebeurde?" · "Hoeveel uur werk je per week?"</p></div><div class="box"><h4>Meningen</h4><p class="dim">"Wat vind je leuk aan je werk?" · "Zou je dit weer doen?"</p></div><div class="box"><h4>Gevoelens</h4><p class="dim">"Was je bang toen...?" · "Wat ging er door je heen, toen...?"</p></div></div><div class="call sum"><b>Om te onthouden (12.2)</b><ul class="lst"><li>Interviewvragen gaan over <b>feiten, meningen</b> of <b>gevoelens</b>.</li><li>Een goed interview bevat een mix van alle drie de soorten vragen.</li></ul></div>'},
{heading:'12.3 Een interview afnemen',html:'<div class="box"><h4>Langere antwoorden krijgen</h4><p>Mensen die geïnterviewd worden, geven soms heel korte antwoorden. Je krijgt vaak <b>langere antwoorden</b> als je:</p><ul class="lst"><li><b>open vragen</b> stelt, en</li><li>niet alleen naar <b>feiten</b> vraagt, maar ook naar <b>meningen</b> en <b>gevoelens</b>.</li></ul></div><div class="call">Tip: open vragen beginnen vaak met "hoe", "wat" of "waarom". Bijvoorbeeld: "Ben je naar de kapper geweest?" wordt "Hoe vind je het om naar de kapper te gaan?"</div><div class="call sum"><b>Om te onthouden (12.3)</b><ul class="lst"><li>Gebruik <b>open vragen</b> en vraag ook naar <b>meningen</b> en <b>gevoelens</b> voor langere, rijkere antwoorden.</li></ul></div>'},
{heading:'12.4 Een interview uitwerken',html:'<div class="box"><h4>Van interview naar artikel</h4><p>Werk je een interview uit tot een artikel, begin dan met een <b>inleiding</b>: wie heb je geïnterviewd en waarom? Daarna volgen de vragen met daaronder de antwoorden.</p></div><div class="box" style="margin-top:1rem"><h4>Van spreektaal naar schrijftaal</h4><p>Praten mensen? Dan gebruiken ze <b>spreektaal</b> (onafgemaakte zinnen, stopwoordjes als "ehhh"). Bij het uitwerken verander je dit in <b>schrijftaal</b>:</p><ul class="lst"><li>Vat lange antwoorden <b>samen</b>.</li><li>Maak <b>korte zinnen</b>.</li><li>Begin met een hoofdletter, eindig met een punt, vraagteken of uitroepteken.</li><li>Haal <b>betekenisloze woordjes</b> weg (ehhh, nou, kijk).</li><li>Schrijf woorden <b>helemaal uit</b>: "even" in plaats van "ff".</li></ul></div><div class="box"><h4>Opmaak en titel</h4><ul class="lst"><li>Gebruik een <b>witregel</b> tussen de inleiding en de eerste vraag, en na elk antwoord.</li><li>Maak de vragen <b>vet</b>.</li><li>Plaats eventueel een <b>foto</b> van de geïnterviewde.</li><li>Bedenk een <b>titel</b>: kort, duidelijk en nieuwsgierig makend, bijvoorbeeld een uitspraak van de geïnterviewde.</li></ul></div><div class="call sum"><b>Om te onthouden (12.4)</b><ul class="lst"><li>Begin een uitgewerkt interview met een <b>inleiding</b>.</li><li>Verander <b>spreektaal in schrijftaal</b>: samenvatten, korte zinnen, geen stopwoordjes.</li><li>Maak het overzichtelijk met witregels, vetgedrukte vragen en een pakkende titel.</li></ul></div>'},
{heading:'12.5 Zakelijke e-mail',html:'<div class="box"><h4>Wanneer schrijf je een zakelijke e-mail?</h4><p>Een <b>zakelijke e-mail</b> stuur je naar bedrijven of personen die je meestal niet kent, bijvoorbeeld over een stage of bijbaantje. Je gebruikt hierin <b>formele taal</b>.</p></div><div class="g2" style="margin-top:1rem"><div class="box"><h4>Inhoud</h4><ul class="lst"><li><b>Inleiding</b>: wie je bent en waarom je mailt.</li><li><b>Middenstuk</b>: je vraag of gewenste informatie.</li><li><b>Slot</b>: een wens of verwachting, bijv. "Ik hoop snel een antwoord te krijgen."</li></ul></div><div class="box"><h4>Vorm</h4><ul class="lst"><li>Vul altijd de <b>onderwerpregel</b> in.</li><li>Begin met een beleefde <b>aanhef</b> + komma: "Beste mevrouw Van Suijlenkom,"</li><li>Spreek de ander aan met <b>"u"</b> en gebruik formele taal.</li><li>Gebruik <b>witregels</b> tussen de onderdelen.</li><li>Controleer op <b>taal- en spelfouten</b>.</li><li>Sluit af met <b>"Met vriendelijke groet,"</b> en je volledige naam.</li></ul></div></div><div class="call sum"><b>Om te onthouden (12.5)</b><ul class="lst"><li>Een zakelijke e-mail heeft een <b>inleiding, middenstuk en slot</b>, en gebruikt <b>formele taal (u)</b>.</li><li>Vul altijd een onderwerpregel in en sluit af met "Met vriendelijke groet" en je naam.</li></ul></div>'}
],
terms:[
['gesloten vraag','Een vraag met maar één kort mogelijk antwoord, vaak ja of nee.',0],
['open vraag','Een vraag die een uitgebreider antwoord uitlokt, vaak beginnend met hoe, wat of waarom.',0],
['interviewvraag naar feiten','Een vraag over wat er gebeurd is of gebeurt.',2],
['interviewvraag naar mening','Een vraag naar wat iemand van iets vindt.',0],
['interviewvraag naar gevoel','Een vraag naar hoe iemand zich voelde of voelt.',0],
['spreektaal','De informele, onafgemaakte manier van praten die mensen gebruiken, met stopwoordjes.',3],
['schrijftaal','De nette, volledige manier van schrijven, zonder stopwoordjes en met complete zinnen.',3],
['zakelijke e-mail','Een formele e-mail aan een bedrijf of onbekend persoon, bijvoorbeeld over een stage.',4],
['aanhef','De beleefde begingroet van een brief of e-mail, zoals "Beste mevrouw..."',4],
['onderwerpregel','De regel in een e-mail waarin kort staat waar de e-mail over gaat.',4]
],
cards:[
['Wat is het verschil tussen een open en een gesloten vraag?','Een gesloten vraag geeft een kort antwoord (vaak ja/nee); een open vraag geeft een uitgebreider antwoord.',0],
['Met welke woorden beginnen open vragen vaak?','Hoe, wat of waarom.',2],
['Welke drie soorten interviewvragen zijn er?','Vragen naar feiten, meningen en gevoelens.',1],
['Hoe krijg je langere antwoorden in een interview?','Door open vragen te stellen en ook naar meningen en gevoelens te vragen.',2],
['Waarmee begin je een uitgewerkt interview?','Met een inleiding: wie je hebt geïnterviewd en waarom.',3],
['Wat doe je met spreektaal als je een interview uitwerkt?','Je verandert het in schrijftaal: samenvatten, korte zinnen, geen stopwoordjes.',3],
['Wat maak je vet in een uitgewerkt interview?','De vragen.',3],
['Wanneer schrijf je een zakelijke e-mail?','Aan bedrijven of mensen die je niet kent, bijvoorbeeld over een stage of bijbaantje.',4],
['Hoe spreek je iemand aan in een zakelijke e-mail?','Met "u", in formele taal.',4],
['Waarmee sluit je een zakelijke e-mail af?','Met "Met vriendelijke groet," en je volledige naam.',4]
],
quiz:[
['Wat is een gesloten vraag?',['Een vraag met een uitgebreid antwoord','Een vraag met maar één kort antwoord, vaak ja/nee','Een vraag over een mening','Een vraag zonder antwoord'],1,'Een gesloten vraag heeft maar één kort mogelijk antwoord, vaak ja of nee.'],
['Waarmee begint een open vraag vaak?',['Ja of nee','Hoe, wat of waarom','Een cijfer','Een naam'],1,'Open vragen beginnen vaak met hoe, wat of waarom.'],
['Welke drie soorten interviewvragen zijn er?',['Feiten, meningen, gevoelens','Feiten, cijfers, namen','Meningen, cijfers, data','Gevoelens, cijfers, feiten'],0,'Interviewvragen gaan over feiten, meningen of gevoelens.'],
['Hoe krijg je vaak langere antwoorden in een interview?',['Door gesloten vragen te stellen','Door open vragen te stellen en naar mening/gevoel te vragen','Door snel achter elkaar te vragen','Door geen vragen te stellen'],1,'Open vragen en vragen naar mening/gevoel leveren vaak langere antwoorden op.'],
['Waarmee begin je een uitgewerkt interview?',['Met de laatste vraag','Met een inleiding','Met de conclusie','Met een zakelijke e-mail'],1,'Je begint met een inleiding: wie je geïnterviewd hebt en waarom.'],
['Wat doe je bij het uitwerken van een interview met stopwoordjes zoals "ehhh"?',['Je laat ze staan voor sfeer','Je haalt ze weg','Je vervangt ze door punten','Je maakt ze vet'],1,'Betekenisloze stopwoordjes haal je weg als je spreektaal omzet naar schrijftaal.'],
['Wat maak je vet in een uitgewerkt interview?',['De inleiding','De vragen','Alleen de titel','Niets'],1,'De vragen maak je vet, zodat het interview overzichtelijk is.'],
['Wanneer stuur je een zakelijke e-mail?',['Aan een goede vriend','Aan een bedrijf of iemand die je niet kent','Alleen aan familie','Nooit, dat doe je altijd mondeling'],1,'Een zakelijke e-mail stuur je aan bedrijven of personen die je meestal niet kent.'],
['Welke aanspreekvorm gebruik je in een zakelijke e-mail?',['Je/jij','U','Hé','Geen aanspreekvorm'],1,'In een zakelijke e-mail spreek je de ander aan met "u".'],
['Waarmee sluit je een zakelijke e-mail netjes af?',['Doei!','Met vriendelijke groet, + je naam','Cu!','Helemaal niet'],1,'Je sluit een zakelijke e-mail af met "Met vriendelijke groet," gevolgd door je volledige naam.'],
['Wat hoort in het middenstuk van een zakelijke e-mail?',['Je naam en de datum','Je vraag of gewenste informatie','Een grappige anekdote','Niets, dat blijft leeg'],1,'In het middenstuk van een zakelijke e-mail geef je aan welke informatie je wilt of stel je je vraag.']
]
});
