import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|tl|1|2', {
title:'Media',
summary:[
{heading:'Apps',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>In dit hoofdstuk leer je kritisch omgaan met media: hoe herken je een startscherm en volgscherm van een app, hoe beoordeel je of informatie betrouwbaar is, hoe brainstorm je online over een idee, hoe ontwerp je een prototype (mock-up) van een app, hoe geef je een pitch en hoe evalueer je je eigen aanpak en product aan het einde van een project.</p></div><div class=\'box\'><h4>Hoe zit een app in elkaar?</h4><p>Een app heeft verschillende schermen waar je doorheen navigeert. Het <b>startscherm</b> is het eerste scherm dat je ziet als je een app of site opent. Vanaf het startscherm kom je via knoppen op <b>volgschermen</b> terecht: schermen die pas verschijnen nadat je ergens op hebt geklikt.</p></div><div class=\'term\'><b>Startscherm</b><span>eerste scherm dat je ziet als je een app of site opent</span></div><div class=\'term\'><b>Volgscherm</b><span>een scherm dat na het startscherm komt; je komt er door op iets in het startscherm te klikken</span></div><div class=\'call\'>Bij het bekijken en beoordelen van een app let je op hoe duidelijk de knoppen zijn en of je makkelijk van het startscherm naar de juiste informatie navigeert.</div>'},
{heading:'Betrouwbaarheid',html:'<div class=\'box\'><h4>Is deze informatie betrouwbaar?</h4><p>Niet alle informatie die je online tegenkomt klopt. Sommige berichten zijn <b>nepnieuws</b>: nieuws dat opzettelijk verspreid wordt, vaak via sociale media, terwijl het niet waar is. Voordat je informatie gebruikt of deelt, controleer je daarom of de bron betrouwbaar is.</p></div><div class=\'term\'><b>Nepnieuws</b><span>nieuws dat opzettelijk verspreid wordt, vaak via sociale media en niet klopt</span></div><div class=\'call sum\'><b>Zo controleer je of informatie betrouwbaar is</b><ul class=\'lst\'><li>Kijk wie de afzender is: is het een bekende, betrouwbare organisatie?</li><li>Controleer of andere bronnen hetzelfde beweren.</li><li>Let op of het bericht bedoeld is om je te overtuigen of te choqueren (een teken van nepnieuws).</li><li>Kijk of de informatie recent en actueel is.</li></ul></div>'},
{heading:'Online brainstormen',html:'<div class=\'box\'><h4>Ideeën verzamelen</h4><p>Bij <b>brainstormen</b> wissel je ideeën uit met anderen. Dat kan ook online, bijvoorbeeld met een gedeeld document of digitaal bord. Het doel is om zoveel mogelijk ideeën te verzamelen, zonder ze meteen te beoordelen.</p></div><div class=\'term\'><b>Brainstormen</b><span>ideeën uitwisselen met anderen om tot een goed plan of ontwerp te komen</span></div><div class=\'call sum\'><b>Zo brainstorm je online</b><ul class=\'lst\'><li>Noteer eerst zelf een paar ideeën.</li><li>Deel je ideeën in een gezamenlijk document of digitaal bord.</li><li>Reageer op de ideeën van anderen en bouw erop voort.</li><li>Selecteer aan het eind samen de beste ideeën.</li></ul></div>'},
{heading:'Een prototype ontwerpen',html:'<div class=\'box\'><h4>Een proefmodel maken</h4><p>Een <b>prototype</b> is een proefmodel van een product. Als je een product wilt maken, bijvoorbeeld een nieuwe auto, dan is het handig om eerst een proefmodel te maken. Zo kun je snel en goedkoop je idee testen, om zo te leren wat werkt en wat niet.</p><p>Een prototype kan van alles zijn: een tekening, een voorwerp van karton, papier of klei, een stripverhaal, een toneelstukje enzovoort. Alles kan, als het maar helpt om een duidelijk beeld te geven van het idee of het product.</p><p>Een prototype van een app noem je ook wel een <b>mock-up</b>: een voorbeeldscherm (of voorbeeldschermen) van de app dat laat zien hoe de app eruit komt te zien en wat de app straks allemaal kan.</p></div><div class=\'term\'><b>Prototype</b><span>een proefmodel van een product, waarmee je je idee snel en goedkoop kunt testen</span></div><div class=\'term\'><b>Mock-up</b><span>een prototype van een app: een voorbeeldscherm dat laat zien hoe de app eruitziet en wat hij kan</span></div><div class=\'term\'><b>Projectsjabloon</b><span>een soort invulvragenlijst die je steeds weer kunt gebruiken bij projecten die op elkaar lijken</span></div><div class=\'call\'>Bij het maken van een mock-up moet je aan heel veel dingen denken. Om zeker te weten dat je niks vergeet, kun je een projectsjabloon invullen.</div>'},
{heading:'Pitchen',html:'<div class=\'box\'><h4>Kort en overtuigend presenteren</h4><p>Bij <b>pitchen</b> presenteer je heel kort, soms zelfs maximaal één minuut. Tijdens het pitchen wil je je publiek overhalen, bijvoorbeeld om jouw product te kopen of jouw idee te steunen.</p></div><div class=\'term\'><b>Pitchen</b><span>heel kort presenteren, waarbij je probeert je publiek te overtuigen van jouw idee of product</span></div><div class=\'call sum\'><b>Zo geef je een goede pitch</b><ul class=\'lst\'><li>Vertel meteen wat je idee of product is en wat het bijzonder maakt.</li><li>Wees kort en bondig: je hebt maar weinig tijd.</li><li>Sluit af met een duidelijke oproep, bijvoorbeeld waarom het publiek \'ja\' moet zeggen.</li></ul></div>'},
{heading:'Evalueren en verslag doen',html:'<div class=\'box\'><h4>Terugkijken op je product en aanpak</h4><p>Aan het einde van een project is het belangrijk om te <b>evalueren</b>: kritisch terugkijken op wat je hebt gemaakt en hoe je te werk bent gegaan. Je bekijkt wat goed ging en wat de volgende keer beter kan.</p></div><div class=\'call sum\'><b>Waar let je op bij evalueren?</b><ul class=\'lst\'><li>Is het product geworden zoals je van tevoren had bedacht?</li><li>Wat vond je van de samenwerking met anderen?</li><li>Welke feedback heb je gekregen en wat heb je daarmee gedaan?</li><li>Wat zou je een volgende keer anders aanpakken?</li></ul></div><div class=\'call waarom\'>Evalueren helpt je om van een project te leren, zodat je het de volgende keer nog beter aanpakt.</div>'}
],
terms:[
['Startscherm','Het eerste scherm dat je ziet als je een app of site opent.',0],
['Volgscherm','Een scherm dat na het startscherm komt; je komt er door op iets in het startscherm te klikken.',0],
['Nepnieuws','Nieuws dat opzettelijk verspreid wordt, vaak via sociale media, terwijl het niet klopt.',1],
['Betrouwbare bron','Een bron waarvan de informatie klopt en die je kunt vertrouwen, bijvoorbeeld omdat het een bekende organisatie is.',1],
['Brainstormen','Ideeën uitwisselen met anderen om tot een goed plan of ontwerp te komen.',2],
['Prototype','Een proefmodel van een product, waarmee je je idee snel en goedkoop kunt testen.',3],
['Mock-up','Een prototype van een app: een voorbeeldscherm dat laat zien hoe de app eruitziet en wat hij kan.',3],
['Projectsjabloon','Een soort invulvragenlijst die je steeds weer kunt gebruiken bij vergelijkbare projecten.',3],
['Pitchen','Heel kort presenteren, waarbij je probeert je publiek te overtuigen van jouw idee of product.',4],
['Evalueren','Kritisch terugkijken op je product en je aanpak: wat ging goed en wat kan beter.',5]
],
cards:[
['Wat is een startscherm?','Het eerste scherm dat je ziet als je een app of site opent.',0],
['Wat is een volgscherm?','Een scherm dat je te zien krijgt nadat je op iets in het startscherm hebt geklikt.',0],
['Wat is nepnieuws?','Nieuws dat opzettelijk verspreid wordt, vaak via sociale media, terwijl het niet klopt.',1],
['Noem één manier om te controleren of informatie betrouwbaar is.','Bijvoorbeeld: controleren of andere bronnen hetzelfde beweren.',1],
['Wat is het doel van brainstormen?','Zoveel mogelijk ideeën verzamelen, zonder ze meteen te beoordelen.',2],
['Wat is een prototype?','Een proefmodel van een product, waarmee je je idee snel en goedkoop kunt testen.',3],
['Hoe noem je een prototype van een app?','Een mock-up.',3],
['Waarom vul je een projectsjabloon in bij het maken van een mock-up?','Om zeker te weten dat je niets vergeet.',3],
['Wat is pitchen?','Heel kort presenteren om je publiek te overtuigen van je idee of product.',4],
['Waar let je op bij het evalueren van een project?','Onder andere op het eindresultaat, de samenwerking en wat je een volgende keer anders zou doen.',5]
],
quiz:[
['Wat is een startscherm?',['Het laatste scherm van een app','Het eerste scherm dat je ziet als je een app opent','Een scherm met alleen reclame','Een scherm dat je nooit ziet'],1,'Het startscherm is het eerste scherm dat je ziet als je een app of site opent.'],
['Wanneer zie je een volgscherm?',['Voordat je de app opent','Nadat je op iets in het startscherm hebt geklikt','Alleen als de app crasht','Nooit, dat bestaat niet'],1,'Een volgscherm komt na het startscherm; je komt erop door iets aan te klikken.'],
['Wat is nepnieuws?',['Nieuws dat altijd grappig is','Nieuws dat opzettelijk verspreid wordt terwijl het niet klopt','Nieuws dat alleen op tv komt','Nieuws dat door de overheid wordt gecontroleerd'],1,'Nepnieuws is nieuws dat opzettelijk verspreid wordt, vaak via sociale media, terwijl het niet waar is.'],
['Wat is een goede manier om betrouwbaarheid te checken?',['Alleen naar de titel kijken','Kijken of andere bronnen hetzelfde beweren','Het bericht meteen delen','Nooit iets controleren'],1,'Je controleert of andere (betrouwbare) bronnen dezelfde informatie geven.'],
['Wat is het doel van brainstormen?',['Meteen het beste idee kiezen','Zoveel mogelijk ideeën verzamelen','Een idee meteen afkeuren','Een tekst schrijven'],1,'Bij brainstormen verzamel je zoveel mogelijk ideeën, zonder ze meteen te beoordelen.'],
['Wat is een prototype?',['Het eindproduct','Een proefmodel van een product','Een reclametekst','Een soort presentatie'],1,'Een prototype is een proefmodel waarmee je je idee kunt testen.'],
['Hoe noem je een prototype van een app?',['Een pitch','Een mock-up','Een startscherm','Een sjabloon'],1,'Een prototype van een app noem je een mock-up.'],
['Waarvoor gebruik je een projectsjabloon?',['Om een pitch te geven','Om niets te vergeten bij het maken van een prototype','Om nepnieuws te herkennen','Om te brainstormen'],1,'Een projectsjabloon is een invulvragenlijst waarmee je zeker weet dat je niets vergeet.'],
['Wat is kenmerkend voor een pitch?',['Hij duurt heel lang','Hij is heel kort en overtuigend','Hij bevat geen mening','Hij wordt altijd schriftelijk gedaan'],1,'Een pitch is een korte, overtuigende presentatie, soms van maximaal één minuut.'],
['Wat doe je bij het evalueren van een project?',['Een nieuw project starten','Terugkijken op je product en je aanpak','Meteen een cijfer geven','Het product weggooien'],1,'Evalueren betekent kritisch terugkijken op wat je hebt gemaakt en hoe je te werk bent gegaan.'],
['Waarom is evalueren nuttig?',['Omdat het verplicht is door de wet','Omdat je ervan leert voor een volgend project','Omdat het niets oplevert','Omdat het sneller gaat dan werken'],1,'Door te evalueren leer je wat goed ging en wat je de volgende keer beter kunt doen.']
]
});
