import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|tl|1|3', {
title:'Fictie',
summary:[
{heading:'Fictie en non-fictie',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>In de cursus Meer dan lezen leerde je over non-fictie. In dit hoofdstuk maak je kennis met <b>fictie</b>: verhalen die de schrijver heeft verzonnen. Je leert het verschil tussen fictie en non-fictie, hoe je je inleeft in personages, hoe je je eigen leessmaak onder woorden brengt en hoe je gedichten leest en begrijpt.</p></div><div class=\'box\'><h4>Wat is fictie?</h4><p>In de cursus Meer dan lezen leer je over <b>non-fictie</b>. Dat zijn teksten waarin de schrijver je bijvoorbeeld informatie geeft over een bepaald onderwerp, je wil overtuigen van zijn mening of wil uitleggen hoe je iets moet doen.</p><p>In deze cursus maak je kennis met <b>fictie</b>. Dat zijn verhalen die de schrijver heeft verzonnen. Het doel van fictie is <b>amuseren</b>: de schrijver wil dat jij zijn verhaal met plezier leest, bijvoorbeeld omdat je het spannend, zielig of aangrijpend vindt. Daardoor kun je bijvoorbeeld even helemaal wegdromen bij een verhaal, aan het denken worden gezet of je voorstellen hoe het is om iemand anders te zijn.</p><p>Als je in een verhaal leest over dingen die in het echt helemaal niet kunnen gebeuren, heb je te maken met een <b>fantasieverhaal</b>. Denk bijvoorbeeld aan Harry Potter. In de meeste verhalen gebeuren dingen die heel goed ook in het echt zouden kunnen gebeuren. Die verhalen noem je <b>realistisch</b>.</p></div><div class=\'term\'><b>Fictie</b><span>verhalen die de schrijver heeft verzonnen, met als doel amuseren</span></div><div class=\'term\'><b>Non-fictie</b><span>teksten die informeren, overtuigen of instrueren, gebaseerd op de werkelijkheid</span></div><div class=\'term\'><b>Fantasieverhaal</b><span>een verhaal over dingen die in het echt niet kunnen gebeuren</span></div><div class=\'term\'><b>Realistisch verhaal</b><span>een verhaal over dingen die ook in het echt zouden kunnen gebeuren</span></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Meer dan lezen § 4 Tekstdoelen en tekstsoorten</div>'},
{heading:'Personages',html:'<div class=\'box\'><h4>Wie speelt een rol in het verhaal?</h4><p>Alle personen die een rol spelen in een verhaal noem je <b>personages</b>. Het belangrijkste personage, degene over wie het hele verhaal gaat, is de <b>hoofdpersoon</b>. Van hem of haar weet je altijd wat hij denkt en voelt. Veel verhalen hebben één hoofdpersoon, maar er zijn ook verhalen met meerdere hoofdpersonen. De andere personages zijn <b>bijfiguren</b>.</p><p>Omdat in verhalen niet alleen wordt beschreven wat personages meemaken, maar ook hoe ze zich voelen, ga je hun gedrag vaak beter begrijpen. Dat noem je <b>inleven</b>.</p></div><div class=\'term\'><b>Personage</b><span>een persoon die een rol speelt in een verhaal</span></div><div class=\'term\'><b>Hoofdpersoon</b><span>het belangrijkste personage, degene over wie het hele verhaal gaat</span></div><div class=\'term\'><b>Bijfiguur</b><span>een ander personage dan de hoofdpersoon</span></div><div class=\'term\'><b>Inleven</b><span>je voorstellen hoe een personage zich voelt, zodat je zijn gedrag beter begrijpt</span></div>'},
{heading:'Smaak',html:'<div class=\'box\'><h4>Wat is jouw leessmaak?</h4><p>Als iemand jou vraagt van wat voor soort films en series jij houdt, kun je dat waarschijnlijk in een paar woorden uitleggen. Zo is het ook met boeken. Om uit te leggen wat jouw smaak is, kun je iets zeggen over:</p><ul class=\'lst\'><li>het <b>onderwerp</b>: datgene waarover het verhaal gaat, bijvoorbeeld voetbal, pesten of vriendschap;</li><li>het <b>genre</b> (spreek uit: zjan-re): het soort verhaal.</li></ul><p>In de bibliotheek staat op de boeken een pictogram dat het genre aanduidt, bijvoorbeeld avonturenverhaal, familie, griezelverhaal, historisch verhaal, humor, liefdesverhaal, oorlogsverhaal, psychologisch verhaal, school of science fiction.</p><p>Sommige mensen noemen <b>psychologische verhalen</b> ook wel <b>probleemboeken</b>. Daarin worstelt de hoofdpersoon met een probleem. Hij is bijvoorbeeld ernstig ziek of zijn ouders gaan scheiden.</p><p>Of je een boek wel of niet leuk vindt, hangt ook af van hoe het boek eruitziet en hoe het is geschreven. Daarnaast kun je zeggen of je meer van fictie of non-fictie houdt, en of je realistische en fantasieverhalen wel of niet leuk vindt.</p></div><div class=\'term\'><b>Genre</b><span>het soort verhaal, bijvoorbeeld avonturenverhaal, griezelverhaal of liefdesverhaal</span></div><div class=\'term\'><b>Probleemboek</b><span>een psychologisch verhaal waarin de hoofdpersoon worstelt met een probleem</span></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Fictie § 1 Fictie en non-fictie, § 2 Personages</div>'},
{heading:'Over gedichten',html:'<div class=\'box\'><h4>Gedichten lezen en voordragen</h4><p>Een gedicht is een bijzondere tekstsoort: gedichten hoeven niet altijd te rijmen, en soms is een gedicht ook mooi te vinden als je het niet helemaal snapt. Gedichten kunnen gaan over gewone dingen of over \'grote\' gevoelens, zoals verdriet, liefde of gemis.</p><p>Als je een gedicht voordraagt, spreek je het uit voor een publiek. Lees het dan niet gewoon voor, maar probeer ook wat langzamer dan je normaal gesproken zou doen, en laat aan het einde van de regel pauzes vallen.</p></div><div class=\'term\'><b>Rijm</b><span>als de laatste stukjes van twee woorden hetzelfde klinken, rijmen ze (bijvoorbeeld: verdriet - niet)</span></div><div class=\'term\'><b>Voordragen</b><span>een gedicht voor een publiek uitspreken</span></div><div class=\'call sum\'><b>Zo draag je een gedicht mooi voor</b><ul class=\'lst\'><li>Lees het gedicht niet zomaar voor, maar spreek het uit voor je publiek.</li><li>Praat wat langzamer dan je normaal gesproken zou doen.</li><li>Laat aan het einde van de regel pauzes vallen.</li></ul></div>'}
],
terms:[
['Fictie','Verhalen die de schrijver heeft verzonnen, met als doel amuseren.',0],
['Non-fictie','Teksten die informeren, overtuigen of instrueren en gebaseerd zijn op de werkelijkheid.',0],
['Amuseren','Het doel van fictie: de schrijver wil dat jij zijn verhaal met plezier leest.',0],
['Fantasieverhaal','Een verhaal over dingen die in het echt niet kunnen gebeuren.',0],
['Realistisch verhaal','Een verhaal over dingen die ook in het echt zouden kunnen gebeuren.',0],
['Personage','Een persoon die een rol speelt in een verhaal.',1],
['Hoofdpersoon','Het belangrijkste personage, degene over wie het hele verhaal gaat.',1],
['Bijfiguur','Een ander personage dan de hoofdpersoon.',1],
['Inleven','Je voorstellen hoe een personage zich voelt, zodat je zijn gedrag beter begrijpt.',1],
['Genre','Het soort verhaal, bijvoorbeeld avonturenverhaal, griezelverhaal of liefdesverhaal.',2],
['Probleemboek','Een psychologisch verhaal waarin de hoofdpersoon worstelt met een probleem.',2],
['Rijm','Als de laatste stukjes van twee woorden hetzelfde klinken, rijmen ze.',3],
['Voordragen','Een gedicht voor een publiek uitspreken.',3]
],
cards:[
['Wat is het verschil tussen fictie en non-fictie?','Fictie is verzonnen en heeft als doel amuseren; non-fictie is gebaseerd op de werkelijkheid en informeert, overtuigt of instrueert.',0],
['Wat is een fantasieverhaal?','Een verhaal over dingen die in het echt niet kunnen gebeuren.',0],
['Wat is een realistisch verhaal?','Een verhaal over dingen die ook in het echt zouden kunnen gebeuren.',0],
['Wat is de hoofdpersoon van een verhaal?','Het belangrijkste personage, degene over wie het hele verhaal gaat.',1],
['Wat is een bijfiguur?','Een ander personage dan de hoofdpersoon.',1],
['Wat betekent \'inleven\' in een personage?','Je voorstellen hoe het personage zich voelt, zodat je zijn gedrag beter begrijpt.',1],
['Waarmee kun je jouw leessmaak omschrijven?','Met het onderwerp en het genre van het boek.',2],
['Hoe noem je een psychologisch verhaal ook wel?','Een probleemboek.',2],
['Wanneer rijmen twee woorden?','Als de laatste stukjes van de woorden hetzelfde klinken.',3],
['Wat is voordragen?','Een gedicht voor een publiek uitspreken.',3],
['Moet een gedicht altijd rijmen?','Nee, gedichten hoeven niet altijd te rijmen.',3]
],
quiz:[
['Wat is het doel van fictie?',['Informeren','Amuseren','Instrueren','Overtuigen'],1,'Het doel van fictie is amuseren: de schrijver wil dat je zijn verhaal met plezier leest.'],
['Wat is non-fictie?',['Verzonnen verhalen','Teksten die informeren, overtuigen of instrueren, gebaseerd op de werkelijkheid','Alleen gedichten','Alleen fantasieverhalen'],1,'Non-fictie is gebaseerd op de werkelijkheid en heeft als doel informeren, overtuigen of instrueren.'],
['Wat is een voorbeeld van een fantasieverhaal?',['Een boek over pesten op school','Harry Potter','Een nieuwsbericht','Een gebruiksaanwijzing'],1,'Harry Potter gaat over dingen die in het echt niet kunnen gebeuren: dat is een fantasieverhaal.'],
['Wat is een realistisch verhaal?',['Een verhaal met sprekende dieren','Een verhaal over dingen die ook in het echt zouden kunnen gebeuren','Een verhaal zonder personages','Een gedicht'],1,'In de meeste verhalen gebeuren dingen die ook in het echt zouden kunnen gebeuren: dat noem je realistisch.'],
['Wie is de hoofdpersoon van een verhaal?',['Elk personage in het verhaal','Het belangrijkste personage, over wie het verhaal gaat','Alleen de schrijver','De persoon op de kaft'],1,'De hoofdpersoon is het belangrijkste personage; van hem of haar weet je altijd wat hij denkt en voelt.'],
['Wat is een bijfiguur?',['De hoofdpersoon','Een ander personage dan de hoofdpersoon','De schrijver van het boek','Het onderwerp van het verhaal'],1,'Een bijfiguur is elk personage dat niet de hoofdpersoon is.'],
['Wat betekent \'inleven\' bij het lezen van fictie?',['Het boek dichtslaan','Je voorstellen hoe een personage zich voelt','Alleen de titel lezen','Het verhaal navertellen'],1,'Inleven betekent dat je je voorstelt hoe een personage zich voelt, waardoor je zijn gedrag beter begrijpt.'],
['Waarmee kun je je leessmaak omschrijven?',['Alleen met de kleur van de kaft','Met het onderwerp en genre van een boek','Met het aantal bladzijden','Met de naam van de uitgever'],1,'Je smaak beschrijf je met het onderwerp (waar het verhaal over gaat) en het genre (het soort verhaal).'],
['Hoe noem je een psychologisch verhaal ook wel?',['Een griezelverhaal','Een probleemboek','Een non-fictieboek','Een gedichtenbundel'],1,'Een psychologisch verhaal, waarin de hoofdpersoon worstelt met een probleem, noem je ook wel een probleemboek.'],
['Wanneer rijmen twee woorden?',['Als ze even lang zijn','Als de laatste stukjes hetzelfde klinken','Als ze met dezelfde letter beginnen','Als ze allebei een werkwoord zijn'],1,'Rijm ontstaat als de laatste stukjes van twee woorden hetzelfde klinken.'],
['Moet een gedicht altijd rijmen om mooi te zijn?',['Ja, altijd','Nee, je kunt een gedicht ook mooi vinden zonder rijm','Ja, anders is het geen gedicht','Nee, gedichten mogen nooit rijmen'],1,'Gedichten hoeven niet te rijmen; je kunt een gedicht ook mooi vinden als het niet rijmt of als je het niet helemaal snapt.'],
['Wat doe je extra als je een gedicht voordraagt?',['Zo snel mogelijk lezen','Langzamer praten en pauzes laten vallen aan het einde van de regel','Het gedicht overslaan','Alleen fluisteren'],1,'Bij het voordragen praat je wat langzamer en laat je pauzes vallen aan het einde van de regel.']
]
});
