import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|tl|1|4', {
title:'Taal',
summary:[
{heading:'Moedertaal',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>In dit hoofdstuk ontdek je hoe bijzonder taal eigenlijk is: je leert over je moedertaal, taal uit je eigen buurt (dialecten), hoe taal in de loop van de tijd verandert, waar taal uit is opgebouwd, het verschil tussen formeel en informeel taalgebruik, letterlijk en figuurlijk taalgebruik, beeldtaal en dyslexie.</p></div><div class=\'box\'><h4>Wat is je moedertaal?</h4><p>Je <b>moedertaal</b> is de taal die je als kind als eerste hebt geleerd, meestal van je ouders. Voor de meeste leerlingen in Nederland is dat Nederlands, maar voor sommige leerlingen is dat een andere taal. Een taal die je later erbij leert en bijna net zo goed leert spreken als je moedertaal, is je <b>tweede taal</b>.</p></div><div class=\'term\'><b>Moedertaal</b><span>de taal die je als kind als eerste hebt geleerd</span></div><div class=\'term\'><b>Tweede taal</b><span>een taal die je later erbij leert en bijna net zo goed leert spreken als je moedertaal</span></div>'},
{heading:'Taal uit de buurt',html:'<div class=\'box\'><h4>Dialecten en streektaal</h4><p>Niet iedereen in Nederland spreekt precies dezelfde taal. Op verschillende plekken in het land worden woorden soms anders uitgesproken of gebruikt men andere woorden voor hetzelfde begrip. Zo\'n taalvariant die typisch is voor een bepaalde regio, noem je een <b>dialect</b> of <b>streektaal</b>.</p></div><div class=\'term\'><b>Dialect</b><span>een taalvariant die typisch is voor een bepaalde regio of streek</span></div><div class=\'call\'>Dialecten laten zien dat taal verbonden is met waar je vandaan komt: ze horen bij de identiteit van een regio.</div>'},
{heading:'Taalverandering',html:'<div class=\'box\'><h4>Taal verandert steeds</h4><p>Taal staat niet stil: ze verandert voortdurend. Er komen nieuwe woorden bij (bijvoorbeeld door nieuwe technologie of trends) en oude woorden verdwijnen langzaam uit gebruik, omdat niemand ze meer gebruikt. Ook de betekenis van woorden kan in de loop van de tijd veranderen.</p></div><div class=\'term\'><b>Taalverandering</b><span>het proces waarbij taal in de loop van de tijd verandert: er komen woorden bij en woorden verdwijnen</span></div><div class=\'call waarom\'>Taal verandert onder andere doordat de maatschappij verandert: nieuwe uitvindingen, nieuwe gewoontes en contact met andere talen zorgen voor nieuwe woorden.</div>'},
{heading:'Bouwstenen',html:'<div class=\'box\'><h4>Waaruit bestaat taal?</h4><p>Taal is opgebouwd uit bouwstenen. Je kunt ze vergelijken met legostukjes. Die stukjes kun je aan elkaar vastmaken. Meerdere stukjes LEGO aan elkaar vormen een bouwwerk. Bij taal zijn de losse legostukjes de <b>letters</b>. Maak je losse letters aan elkaar, dan heb je een <b>woord</b>. Je kunt een woord verdelen in <b>lettergrepen</b>. Een lettergreep is een groepje letters dat samen één klank maakt. Maak je woorden aan elkaar, dan heb je een zin. En als je zinnen aan elkaar maakt, dan wordt het een tekst.</p><p>Letters zijn in een volgorde gezet, zodat ze makkelijker te gebruiken zijn. Dit heet het <b>alfabet</b>. Ons alfabet bestaat uit 26 letters.</p><p>Sommige talen gebruiken geen letters, maar <b>karakters</b>. Een karakter is een teken dat een klank of begrip weergeeft. Het Chinese karakterschrift heeft de meeste tekens: tienduizenden karakters, waarvan een groot deel niet meer gebruikt wordt.</p><p>De richting waarin je leest en schrijft, heet de <b>schrijfrichting</b>. In de meeste talen lezen en schrijven we van links naar rechts, maar bijvoorbeeld het Arabisch wordt van rechts naar links gelezen en geschreven, en Chinees lees je van boven naar beneden.</p></div><div class=\'term\'><b>Alfabet</b><span>de verzameling letters van een taal</span></div><div class=\'term\'><b>Karakter</b><span>een teken dat een klank of begrip weergeeft (bijvoorbeeld in het Chinees)</span></div><div class=\'term\'><b>Lettergreep</b><span>een groepje letters dat samen één klank maakt</span></div><div class=\'term\'><b>Schrijfrichting</b><span>de richting waarin je een taal leest en schrijft</span></div>'},
{heading:'Formeel en informeel',html:'<div class=\'box\'><h4>Hoe pas je je taalgebruik aan?</h4><p>Je praat en schrijft niet op dezelfde manier tegen iedereen. Tegen vrienden gebruik je vaak <b>informele taal</b>: makkelijke, spreektaalachtige woorden en de aanspreekvorm \'je\' of \'jij\'. Tegen bijvoorbeeld een docent, een onbekende volwassene of in een officiële brief gebruik je <b>formele taal</b>: nettere woorden en vaak de beleefdheidsvorm \'u\'.</p></div><div class=\'term\'><b>Formele taal</b><span>taal voor serieuze, officiële situaties, vaak met \'u\' als aanspreekvorm</span></div><div class=\'term\'><b>Informele taal</b><span>taal voor situaties met bijvoorbeeld vrienden en familie, vaak met \'je\'/\'jij\'</span></div><div class=\'call sum\'><b>Bij het kiezen van formeel of informeel taalgebruik let je op</b><ul class=\'lst\'><li>wie je publiek is (bijvoorbeeld leeftijd en relatie tot jou);</li><li>de situatie: is het officieel of juist ontspannen?</li><li>de aanspreekvorm: \'je/jij\' (informeel) of \'u\' (formeel).</li></ul></div>'},
{heading:'Letterlijk en figuurlijk',html:'<div class=\'box\'><h4>Zeg je het echt zo, of bedoel je iets anders?</h4><p>Bij <b>letterlijk taalgebruik</b> zeg je iets zoals het is volgens de letter: als iemand zegt \'ik lach van blijdschap\', dan is dat een feit. Bij <b>figuurlijk taalgebruik</b> zeg je iets met fantasie: je bedoelt iets anders dan wat er letterlijk staat. Bijvoorbeeld: \'ik schrok me een hoedje\' betekent niet dat er letterlijk een hoedje verscheen, maar dat je erg schrok.</p><p>Bij figuurlijk taalgebruik gebruik je vaak vaste uitdrukkingen, zoals \'een wit voetje halen\' of \'iemand de kop koud maken\'.</p></div><div class=\'term\'><b>Letterlijk taalgebruik</b><span>taal waarmee je precies bedoelt wat er staat</span></div><div class=\'term\'><b>Figuurlijk taalgebruik</b><span>taal waarmee je iets anders bedoelt dan wat er staat</span></div>'},
{heading:'Beeldtaal',html:'<div class=\'box\'><h4>Communiceren met beelden</h4><p><b>Beeldtaal</b> helpt ons om snel te kunnen zien wat de bedoeling is. Overal worden tekens gebruikt om mensen iets te vertellen: in het verkeer, online, op de televisie. Beelden geven snel informatie.</p><p>In het verkeer kennen we veel afspraken. Als die afspraken er niet zouden zijn, dan zouden er ongelukken kunnen gebeuren. Deze afspraken worden weergegeven met tekens, <b>verkeersborden</b>. Als je die tekens herkent, weet je wat je moet doen in het verkeer.</p><p>Een andere beeldtaal is de taal van de <b>emoji</b>. De \'e\' in het woord emoji betekent \'afbeelding\' en \'moji\' betekent karakter of schriftteken. Emoji\'s komen oorspronkelijk uit Japan, maar worden nu over de hele wereld gebruikt.</p><p>Naast verkeerstekens en emoji\'s bestaat er nog veel meer beeldtaal, zoals <b>pictogrammen</b>: eenvoudige afbeeldingen en symbolen die de plaats innemen van tekst. Pictogrammen worden overal gebruikt om regels aan te geven, bijvoorbeeld een wasvoorschrift op een kledinglabel, of een kijkwijzer bij een film.</p></div><div class=\'term\'><b>Beeldtaal</b><span>taal in beelden</span></div><div class=\'term\'><b>Pictogram</b><span>een symbool of eenvoudig plaatje dat een tekst vervangt</span></div><div class=\'term\'><b>Emoji</b><span>een plaatje dat je bijvoorbeeld in een appje gebruikt om iets duidelijk te maken</span></div>'},
{heading:'Dyslexie',html:'<div class=\'box\'><h4>Wat is dyslexie?</h4><p><b>Dyslexie</b> is een aandoening waarbij iemand moeite heeft met het goed en snel lezen en/of spellen van woorden, doordat de informatie niet goed wordt verwerkt in de hersenen. Dyslexie heeft dus niets te maken met hoe slim iemand is. Mensen met dyslexie kunnen vaak wel goed leren lezen en schrijven met de juiste hulp en extra tijd.</p></div><div class=\'term\'><b>Dyslexie</b><span>het niet goed kunnen lezen en schrijven van letters, woorden en zinnen, doordat de informatie niet goed wordt verwerkt in de hersenen</span></div>'}
],
terms:[
['Moedertaal','De taal die je als kind als eerste hebt geleerd.',0],
['Tweede taal','Een taal die je later erbij leert en bijna net zo goed leert spreken als je moedertaal.',0],
['Dialect','Een taalvariant die typisch is voor een bepaalde regio of streek.',1],
['Taalverandering','Het proces waarbij taal in de loop van de tijd verandert: er komen woorden bij en woorden verdwijnen.',2],
['Alfabet','De verzameling letters van een taal.',3],
['Karakter','Een teken dat een klank of begrip weergeeft, zoals in het Chinees.',3],
['Lettergreep','Een groepje letters dat samen één klank maakt.',3],
['Schrijfrichting','De richting waarin je een taal leest en schrijft.',3],
['Formele taal','Taal voor serieuze, officiële situaties, vaak met \'u\' als aanspreekvorm.',4],
['Informele taal','Taal voor situaties met bijvoorbeeld vrienden en familie, vaak met \'je\' of \'jij\'.',4],
['Letterlijk taalgebruik','Taal waarmee je precies bedoelt wat er staat.',5],
['Figuurlijk taalgebruik','Taal waarmee je iets anders bedoelt dan wat er letterlijk staat.',5],
['Beeldtaal','Taal in beelden.',6],
['Pictogram','Een symbool of eenvoudig plaatje dat een tekst vervangt.',6],
['Emoji','Een plaatje dat je bijvoorbeeld in een appje gebruikt om iets duidelijk te maken.',6],
['Dyslexie','Het niet goed kunnen lezen en schrijven van letters, woorden en zinnen, doordat informatie niet goed verwerkt wordt in de hersenen.',7]
],
cards:[
['Wat is je moedertaal?','De taal die je als kind als eerste hebt geleerd.',0],
['Wat is een dialect?','Een taalvariant die typisch is voor een bepaalde regio of streek.',1],
['Wat gebeurt er bij taalverandering?','Er komen nieuwe woorden bij en oude woorden verdwijnen uit gebruik.',2],
['Wat is de kleinste bouwsteen van taal?','De letter.',3],
['Wat is een lettergreep?','Een groepje letters dat samen één klank maakt.',3],
['Wat gebruikt het Chinees in plaats van letters?','Karakters.',3],
['Welke aanspreekvorm hoort bij formele taal?','\'U\'.',4],
['Wanneer gebruik je informele taal?','Bijvoorbeeld tegen vrienden en familie.',4],
['Wat is letterlijk taalgebruik?','Taal waarmee je precies bedoelt wat er staat.',5],
['Wat betekent \'ik schrok me een hoedje\' figuurlijk?','Dat je erg schrok (niet dat er letterlijk een hoedje verscheen).',5],
['Wat is een pictogram?','Een symbool of eenvoudig plaatje dat een tekst vervangt.',6],
['Waar komt de emoji oorspronkelijk vandaan?','Uit Japan.',6],
['Wat is dyslexie?','Het niet goed kunnen lezen en schrijven doordat informatie niet goed verwerkt wordt in de hersenen.',7]
],
quiz:[
['Wat is je moedertaal?',['De taal die je op school leert','De taal die je als kind als eerste hebt geleerd','Een taal die je later erbij leert','De officiële taal van een land'],1,'Je moedertaal is de taal die je als kind als eerste hebt geleerd.'],
['Wat is een dialect?',['Een geheime taal','Een taalvariant die typisch is voor een bepaalde regio','Een oude, uitgestorven taal','Een taal met alleen karakters'],1,'Een dialect is een taalvariant die hoort bij een bepaalde streek.'],
['Wat is taalverandering?',['Een taal die nooit verandert','Het proces waarbij taal in de loop van de tijd verandert','Het leren van een tweede taal','Het spreken van een dialect'],1,'Taal verandert voortdurend: er komen woorden bij en woorden verdwijnen.'],
['Waaruit bestaat een woord volgens de theorie over bouwstenen?',['Uit zinnen','Uit letters','Uit teksten','Uit alinea\'s'],1,'Letters zijn de bouwstenen; meerdere letters samen vormen een woord.'],
['Wat is een lettergreep?',['Een heel woord','Een groepje letters dat samen één klank maakt','Een leesteken','Een zin'],1,'Een lettergreep is een groepje letters dat samen één klank vormt.'],
['Wat gebruikt het Chinese schrift?',['Alleen het Latijnse alfabet','Karakters','Alleen emoji\'s','Geen tekens'],1,'Het Chinees gebruikt karakters in plaats van een alfabet met letters.'],
['In welke richting lees en schrijf je Arabisch?',['Van links naar rechts','Van rechts naar links','Van boven naar beneden','Van onder naar boven'],1,'Arabisch wordt van rechts naar links gelezen en geschreven.'],
['Welke aanspreekvorm past bij formele taal?',['Je/jij','U','Hé','Doei'],1,'Bij formele taal gebruik je meestal de beleefdheidsvorm \'u\'.'],
['Wanneer gebruik je waarschijnlijk informele taal?',['In een sollicitatiebrief','In een appje aan een vriend','In een officiële e-mail aan de directeur','In een zakelijke brief'],1,'Tegen vrienden gebruik je meestal informele, spreektaalachtige taal.'],
['Wat is letterlijk taalgebruik?',['Taal met veel uitdrukkingen','Taal waarmee je precies bedoelt wat er staat','Taal die altijd rijmt','Taal in beelden'],1,'Bij letterlijk taalgebruik bedoel je precies wat er staat.'],
['Wat betekent figuurlijk taalgebruik?',['Je bedoelt precies wat er staat','Je bedoelt iets anders dan wat er letterlijk staat','Je gebruikt alleen cijfers','Je spreekt in een dialect'],1,'Bij figuurlijk taalgebruik bedoel je iets anders dan wat er letterlijk staat, zoals bij een uitdrukking.'],
['Wat is een pictogram?',['Een lang verhaal','Een symbool dat een tekst vervangt','Een soort dialect','Een lettergreep'],1,'Een pictogram is een eenvoudig symbool of plaatje dat de plaats van tekst inneemt.'],
['Waar komt het woord \'emoji\' vandaan?',['Uit het Engels','Uit het Japans','Uit het Frans','Uit het Arabisch'],1,'Emoji\'s komen oorspronkelijk uit Japan; \'e\' betekent afbeelding en \'moji\' karakter.'],
['Wat is dyslexie?',['Een taal die uitgestorven is','Een aandoening waarbij lezen en spellen moeilijk gaat door verwerking in de hersenen','Een dialect uit het zuiden','Een soort beeldtaal'],1,'Dyslexie is het niet goed kunnen lezen en schrijven doordat informatie niet goed verwerkt wordt in de hersenen.'],
['Zegt dyslexie iets over hoe slim iemand is?',['Ja, mensen met dyslexie zijn minder slim','Nee, dyslexie heeft niets te maken met intelligentie','Ja, altijd','Alleen bij volwassenen'],1,'Dyslexie heeft niets te maken met hoe slim iemand is.']
]
});
