import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|tl|1|8', {
title:'Handig!',
summary:[
{heading:'Feedback geven en ontvangen',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>Achter in het boek staat het onderdeel Handig!. Hier vind je overzichtelijke stappenplannen en schema\'s die je steeds weer kunt gebruiken: voor feedback geven, lezen, schrijven, spreken, werkwoordspelling, woorden raden en het stellen van 5w+h-vragen.</p></div><div class=\'box\'><h4>Hoe geef en ontvang je feedback?</h4><p><b>Feedback</b> geven betekent dat je iemand vertelt wat je van zijn werk vindt: wat goed gaat (een <b>top</b>) en wat beter kan (een <b>tip</b>). Goede feedback helpt de ander om zijn werk te verbeteren.</p></div><div class=\'call sum\'><b>Zo geef je goede feedback</b><ul class=\'lst\'><li>Begin met iets positiefs: een top.</li><li>Geef daarna een concrete tip: wat kan er beter, en hoe dan?</li><li>Wees eerlijk, maar ook vriendelijk.</li></ul><b>Zo ontvang je feedback</b><ul class=\'lst\'><li>Luister rustig naar de feedback, zonder meteen in de verdediging te gaan.</li><li>Vraag door als iets niet duidelijk is.</li><li>Bedenk wat je met de feedback gaat doen om je werk te verbeteren.</li></ul></div><div class=\'term\'><b>Top</b><span>iets wat goed ging bij het werk van een ander</span></div><div class=\'term\'><b>Tip</b><span>een concreet advies om het werk van een ander te verbeteren</span></div>'},
{heading:'Stappenplan lezen',html:'<div class=\'box\'><h4>Een tekst zelfstandig begrijpen</h4><p>Dit stappenplan gebruik je om een tekst zonder vragen goed te lezen en te begrijpen. Het zet alles wat je in Meer dan lezen hebt geleerd op een rijtje.</p></div><div class=\'call sum\'><b>Stappenplan lezen</b><ol class=\'num\'><li><b>Oriënterend lezen:</b> markeer de titel en tussenkopjes, bekijk de afbeelding, noteer het onderwerp en maak een woordweb.</li><li><b>Globaal lezen:</b> bepaal de inleiding en het slot; de rest is het middenstuk.</li><li><b>Precies lezen:</b> zoek onbekende woorden op met een woordraadstrategie of woordenboek, noteer de deelonderwerpen, het tekstdoel en de tekstsoort.</li><li><b>Bijna klaar:</b> noteer de hoofdgedachte.</li></ol></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Meer dan lezen § 1 t/m 6</div>'},
{heading:'Stappenplan schrijven',html:'<div class=\'box\'><h4>Een tekst voorbereiden en schrijven</h4><p>Dit stappenplan helpt je om gestructureerd een tekst te schrijven, van voorbereiding tot een afgeronde tekst met een duidelijke inleiding, middenstuk en slot.</p></div><div class=\'call sum\'><b>Stappenplan schrijven</b><ol class=\'num\'><li>Bepaal het onderwerp, het tekstdoel en je publiek.</li><li>Verzamel informatie en bedenk deelonderwerpen, bijvoorbeeld met de 5w+h-vragen.</li><li>Maak een bouwplan: welk deelonderwerp komt in welke alinea?</li><li>Schrijf de inleiding: maak de lezer nieuwsgierig en noem het onderwerp.</li><li>Schrijf het middenstuk: één deelonderwerp per alinea.</li><li>Schrijf het slot: herhaal kort het belangrijkste.</li><li>Lees je tekst na en verbeter spelling- en zinsfouten.</li></ol></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Meer dan lezen § 5 Inleiding, middenstuk en slot en § 6 Deelonderwerpen</div>'},
{heading:'Stappenplan spreken (presentatie geven)',html:'<div class=\'box\'><h4>Een presentatie voorbereiden en geven</h4><div class=\'call sum\'><b>Stap 1: Voorbereiden</b><ol class=\'num\'><li>Schrijf het onderwerp van je presentatie op.</li><li>Bedenk wat je over het onderwerp wilt vertellen in het middenstuk: gebruik de 5w+h-vragen en zoek het antwoord op je vragen.</li><li>Maak een spreekkaartje per vraag met de belangrijkste informatie in steekwoorden, en bedenk de volgorde.</li><li>Maak een spreekkaartje voor de inleiding: waarover gaat je presentatie en waarom heb je dit onderwerp gekozen?</li><li>Maak een spreekkaartje voor het slot: rond af, bijvoorbeeld met een korte samenvatting of je mening.</li><li>Zoek afbeeldingen of voorwerpen die je presentatie duidelijker of aantrekkelijker maken.</li><li>Gebruik bij een powerpoint niet te veel tekst op een dia; blijf je spreekkaartjes gebruiken.</li><li>Oefen je presentatie, bijvoorbeeld voor je ouders of een klasgenoot.</li></ol><b>Stap 2: Presentatie geven</b><ul class=\'lst\'><li>Praat rustig, duidelijk en hard genoeg.</li><li>Kijk zoveel mogelijk naar je publiek en niet te veel op je spreekkaartjes of dia\'s.</li><li>Blijf niet helemaal stil staan, maar gebruik je lichaam, handen en gezichtsuitdrukking.</li><li>Laat afbeeldingen of voorwerpen zien en vertel er iets over.</li><li>Vraag aan het eind of je publiek vragen heeft. Zo ja, beantwoord ze.</li></ul></div></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Thema A § 7 Stemgebruik en Thema B § 4 Een presentatie geven</div>'},
{heading:'Schema werkwoordspelling',html:'<div class=\'box\'><h4>Alles op een rijtje</h4><p>Dit schema helpt je om snel te bepalen hoe je een werkwoordsvorm moet spellen.</p></div><div class=\'call sum\'><b>Is het werkwoord de persoonsvorm?</b><p><b>Ja, persoonsvorm</b> → kies tegenwoordige tijd (tt) of verleden tijd (vt):</p><ul class=\'lst\'><li><b>tt:</b> ik-vorm (bij ik, en bij je/jij achter de pv), ik-vorm + t (voor de rest, enkelvoud) of het hele werkwoord (meervoud).</li><li><b>vt, zwak werkwoord:</b> ik-vorm + -de(n) of -te(n). Twijfel je? Gebruik \'t ex-fokschaap.</li><li><b>vt, sterk werkwoord:</b> schrijf het woord zo kort mogelijk (de veranderde klankvorm).</li></ul><p><b>Nee, geen persoonsvorm</b> → het is een voltooid deelwoord of het hele werkwoord (infinitief):</p><ul class=\'lst\'><li><b>Voltooid deelwoord, zwak werkwoord:</b> maak het woord langer. Hoor je een -d, dan schrijf je -d; hoor je een -t, dan schrijf je -t. Twijfel je? Gebruik \'t ex-fokschaap.</li><li><b>Voltooid deelwoord, sterk werkwoord:</b> zo kort mogelijk, als bijvoeglijk naamwoord.</li><li><b>Heel werkwoord (infinitief):</b> het hele werkwoord, eindigend op -en.</li></ul></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Spelling § 8 t/m § 12</div>'},
{heading:'Overzicht woordraadstrategieën',html:'<div class=\'box\'><h4>Wat doe je bij een onbekend woord?</h4><p>Dit overzicht herhaalt de strategieën die je kunt gebruiken als je een woord tijdens het lezen niet kent.</p></div><div class=\'call sum\'><b>Overzicht woordraadstrategieën</b><ol class=\'num\'><li>Lees de zin (en de zinnen eromheen) nog een keer.</li><li>Kijk naar het woord zelf: ken je een deel ervan, of lijkt het op een woord dat je wel kent?</li><li>Knip het woord in stukjes.</li><li>Sla het woord over en lees verder.</li><li>Zoek het op in een (online) woordenboek.</li></ol></div><div class=\'call link\'><b>Dit bouwt voort op:</b> Meer dan lezen § 1 Onbekende woorden</div>'},
{heading:'5w+h-vragen',html:'<div class=\'box\'><h4>Informatie ordenen met vragen</h4><p>De <b>5w+h-vragen</b> zijn zes vragen waarmee je snel de belangrijkste informatie uit een tekst haalt, of waarmee je informatie verzamelt voor je eigen tekst of presentatie.</p></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Vraag</th><th>Geeft informatie over...</th></tr><tr><td>Wie?</td><td>de personen die iets doen</td></tr><tr><td>Wat?</td><td>wat er gebeurt</td></tr><tr><td>Waar?</td><td>de plaats</td></tr><tr><td>Wanneer?</td><td>het moment of de tijd</td></tr><tr><td>Waarom?</td><td>de reden</td></tr><tr><td>Hoe?</td><td>de manier waarop iets gebeurt</td></tr></table></div><div class=\'call\'>De 5w+h-vragen zijn handig om een tekst samen te vatten en om hoofd- en bijzaken van elkaar te onderscheiden.</div><div class=\'call link\'><b>Dit bouwt voort op:</b> Thema B § 3 De 5w+h-vragen</div>'}
],
terms:[
['Feedback','Wat je van iemands werk vindt: een combinatie van tops (wat goed ging) en tips (wat beter kan).',0],
['Top','Iets wat goed ging bij het werk van een ander.',0],
['Tip','Een concreet advies om het werk van een ander te verbeteren.',0],
['Stappenplan','Een vaste reeks stappen die je helpt om een taak (zoals lezen, schrijven of spreken) systematisch aan te pakken.',1],
['Bouwplan','Een schema waarin je noteert welk deelonderwerp in welke alinea van je tekst komt.',2],
['Spreekkaartje','Een kaartje met steekwoorden dat je gebruikt als geheugensteun tijdens een presentatie.',3],
['Voltooid deelwoord','De werkwoordsvorm die je gebruikt bij bijvoorbeeld \'heeft ... gedaan\'; bij zwakke werkwoorden eindigend op -d of -t.',4],
['Heel werkwoord (infinitief)','De onvervoegde vorm van een werkwoord, eindigend op -en, bijvoorbeeld lopen.',4],
['5w+h-vragen','Wie, wat, waar, wanneer, waarom en hoe: zes vragen om informatie te ordenen.',6],
['Woordraadstrategie (overzicht)','Een van de manieren om de betekenis van een onbekend woord te achterhalen zonder woordenboek.',5]
],
cards:[
['Waarmee begin je bij het geven van feedback?','Met iets positiefs: een top.',0],
['Wat is een tip bij feedback geven?','Een concreet advies om het werk te verbeteren.',0],
['Wat is de eerste stap van het stappenplan lezen?','Oriënterend lezen.',1],
['Wat schrijf je als eerste stap van het stappenplan schrijven?','Je bepaalt het onderwerp, het tekstdoel en je publiek.',2],
['Waarmee bereid je een presentatie voor volgens Handig?','Met spreekkaartjes per vraag/onderdeel, gebaseerd op de 5w+h-vragen.',3],
['Waar moet je op letten tijdens het geven van een presentatie?','Onder andere: rustig en duidelijk praten, naar je publiek kijken, je lichaam gebruiken.',3],
['Wat gebruik je bij twijfel over -d of -t in werkwoordspelling?','\'t ex-fokschaap.',4],
['Noem twee woordraadstrategieën uit het overzicht.','Bijvoorbeeld: de zin nog een keer lezen en het woord in stukjes knippen.',5],
['Welke zes vragen horen bij de 5w+h-vragen?','Wie, wat, waar, wanneer, waarom en hoe.',6],
['Waarvoor gebruik je de 5w+h-vragen?','Om de belangrijkste informatie uit een tekst te halen of te ordenen voor je eigen tekst.',6]
],
quiz:[
['Wat is een top bij feedback geven?',['Iets wat beter kan','Iets wat goed ging','Een cijfer','Een vraag'],1,'Een top is iets wat goed ging bij het werk van een ander.'],
['Hoe reageer je het beste als je feedback ontvangt?',['Meteen boos worden','Rustig luisteren en eventueel doorvragen','De feedback negeren','Meteen tegenspreken'],1,'Je luistert rustig naar feedback en vraagt door als iets niet duidelijk is.'],
['Wat is de eerste stap van het stappenplan lezen?',['Precies lezen','Oriënterend lezen','De hoofdgedachte noteren','Globaal lezen'],1,'Je begint met oriënterend lezen om het onderwerp te vinden.'],
['Wat maak je bij het stappenplan schrijven om te bepalen welk deelonderwerp in welke alinea komt?',['Een woordweb','Een bouwplan','Een spreekkaartje','Een feedbackformulier'],1,'Met een bouwplan bepaal je de indeling van je tekst in alinea\'s.'],
['Wat gebruik je als geheugensteun tijdens een presentatie?',['Een spreekkaartje','Een woordenboek','Een bouwplan','Een feedbackformulier'],0,'Een spreekkaartje met steekwoorden helpt je tijdens het presenteren.'],
['Waar moet je bij het geven van een presentatie vooral naar kijken?',['Naar je spreekkaartjes','Naar de grond','Naar je publiek','Naar de deur'],2,'Je kijkt zoveel mogelijk naar je publiek en niet te veel op je spreekkaartjes.'],
['Wanneer gebruik je in het schema werkwoordspelling \'t ex-fokschaap?',['Bij lidwoorden','Bij twijfel tussen -d(e) en -t(e) bij zwakke werkwoorden','Bij hoofdletters','Bij verkleinwoorden'],1,'\'t ex-fokschaap helpt je bepalen of je -te(n) of -de(n) moet schrijven bij zwakke werkwoorden.'],
['Wat doe je als eerste woordraadstrategie bij een onbekend woord?',['Het woordenboek pakken','De zin nog een keer lezen','Het woord overslaan','Het opzoeken op internet'],1,'De eerste strategie is de zin (en de omliggende tekst) nog eens lezen.'],
['Welke vraag hoort niet bij de 5w+h-vragen?',['Wie?','Waarom?','Hoeveel?','Hoe?'],2,'De 5w+h-vragen zijn: wie, wat, waar, wanneer, waarom en hoe. \'Hoeveel\' hoort daar niet bij.'],
['Waarvoor zijn de 5w+h-vragen handig?',['Om een gedicht te maken','Om informatie samen te vatten en te ordenen','Om spelfouten te vinden','Om hoofdletters te herkennen'],1,'Met de 5w+h-vragen haal je snel de belangrijkste informatie uit een tekst of orden je je eigen tekst.'],
['Wat is een voltooid deelwoord?',['Het hele werkwoord (infinitief)','De werkwoordsvorm die je gebruikt bij bijvoorbeeld \'heeft ... gedaan\'','Alleen de ik-vorm','Een bijvoeglijk naamwoord'],1,'Het voltooid deelwoord gebruik je bijvoorbeeld na \'heeft\' of \'is\', zoals in \'heeft gedaan\'.']
]
});
