import { registerChapter } from '../../../registry.js';

registerChapter('engels|bbl|2|2', {
title:'Health',
summary:[
{heading:'Bij de dokter en ziektes',html:'<div class=\'box\'><h4>Waar dit hoofdstuk over gaat</h4><p>In dit hoofdstuk leer je woorden over gezondheid, de dokter, ziektes en klachten. Je leert ook hoe je vertelt wat er gebeurde terwijl iets anders al aan de gang was (<b>past continuous</b>), en hoe je advies geeft met <b>can</b>, <b>could</b> en <b>should</b>.</p></div><div class=\'box\'><h4>Bij de dokter</h4><p>Deze woorden gebruik je als je het hebt over een doktersbezoek.</p></div><div class=\'g2\'><div class=\'box\'><h4>At the doctor\'s</h4><ul class=\'lst\'><li><b>appointment</b> - afspraak</li><li><b>crutches</b> - krukken</li><li><b>dentist</b> - tandarts</li><li><b>(to) examine</b> - onderzoeken</li><li><b>(to) feel worse</b> - zich slechter voelen</li><li><b>(to) get better</b> - beter worden</li><li><b>(to) hurt</b> - pijn doen</li><li><b>plaster</b> - pleister, gips</li><li><b>waiting room</b> - wachtkamer</li><li><b>x-ray</b> - r&ouml;ntgenfoto</li></ul></div><div class=\'box\'><h4>Illnesses and injuries</h4><ul class=\'lst\'><li><b>(to) be ill</b> - ziek zijn</li><li><b>(to) bleed</b> - bloeden</li><li><b>(to) bump</b> - stoten</li><li><b>(to) burn</b> - verbranden</li><li><b>(to) cough</b> - hoesten</li><li><b>(to) cut</b> - snijden</li><li><b>(to) faint</b> - flauwvallen</li><li><b>(to) feel sick</b> - zich misselijk voelen</li><li><b>(to) slip</b> - uitglijden</li><li><b>(to) throw up</b> - overgeven</li></ul></div></div><div class=\'call\'>Andere nuttige woorden: <b>ankle</b> (enkel), <b>swollen</b> (opgezwollen), <b>pale</b> (bleek), <b>painful</b> (pijnlijk).</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Ken het verschil tussen \'hurt\' (pijn doen), \'feel sick\' (misselijk zijn) en \'bleed\' (bloeden).</li><li>\'Ill\' en \'sick\' lijken op elkaar maar zijn geen exacte vertaling van hetzelfde woord: ill = ziek, feel sick = misselijk zijn.</li></ul></div>'},
{heading:'Gezondheidsklachten en advies',html:'<div class=\'box\'><h4>Health conditions</h4><p>Zo beschrijf je een klacht of aandoening.</p><ul class=\'lst\'><li><b>black eye</b> - blauw oog</li><li><b>(to) feel dizzy</b> - duizelig zijn</li><li><b>(to) feel miserable</b> - zich ellendig voelen</li><li><b>(to) have a cold</b> - verkouden zijn</li><li><b>(to) have a fever</b> - koorts hebben</li><li><b>(to) have the flu</b> - de griep hebben</li><li><b>headache</b> - hoofdpijn</li><li><b>runny nose</b> - loopneus</li><li><b>sore throat</b> - keelpijn</li><li><b>toothache</b> - kiespijn, tandpijn</li></ul></div><div class=\'box\'><h4>Tips and advice</h4><ul class=\'lst\'><li><b>(to) breathe in/out</b> - in-/uitademen</li><li><b>(to) cure</b> - genezen</li><li><b>(to) cut down on</b> - verminderen</li><li><b>(to) hang in there</b> - volhouden</li><li><b>(to) heal</b> - herstellen, genezen</li><li><b>(to) improve</b> - verbeteren</li><li><b>(to) rest</b> - rusten</li><li><b>(to) take a break</b> - een pauze nemen</li><li><b>(to) take it easy</b> - het rustig aan doen</li><li><b>(to) worry</b> - zich zorgen maken</li></ul></div><div class=\'call\'>Voorbeeldzinnen om een klacht te bespreken: <i>You look a bit pale. I think you need to see your doctor.</i> &mdash; <i>He examined me but couldn\'t find anything.</i> &mdash; <i>She said I should take these pills three times a day.</i></div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Klachten met \'have\' (have a cold, have a fever, have the flu) en met \'feel\' (feel dizzy, feel miserable) worden vaak door elkaar gehaald: let op welk werkwoord erbij hoort.</li><li>Bij advies gebruik je vaak \'should\' samen met deze tips-woorden.</li></ul></div>'},
{heading:'Grammar 3: de past continuous',html:'<div class=\'box\'><h4>Wanneer gebruik je de past continuous?</h4><p>Je gebruikt de <b>past continuous</b> om te praten over iets dat in het verleden gebeurde en een langere tijd aan de gang was. Je maakt de past continuous met <b>was/were + werkwoord + -ing</b>.</p></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Onderwerp</th><th>Vorm</th><th>Voorbeeld</th></tr><tr><td>I / he / she / it</td><td>was + -ing</td><td>I was waiting.</td></tr><tr><td>you / we / they</td><td>were + -ing</td><td>They were working out.</td></tr></table></div><div class=\'call\'>Voorbeeldzinnen: <i>I suddenly had a pain in my back.</i> &mdash; <i>We were warming up when the ball hit Sarah.</i> &mdash; <i>They were working out when the music stopped.</i> De past continuous beschrijft vaak de langere actie, de past simple de korte actie die deze onderbreekt.</div><div class=\'call warn\'><b>Veelgemaakte fout:</b> was/were vergeten voor het werkwoord. Fout: <i>I waiting for the doctor.</i> Goed: <i>I was waiting for the doctor.</i></div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Past continuous = was/were + werkwoord + -ing.</li><li>Gebruik het voor een langere, lopende actie in het verleden, vaak samen met een past simple-zin die de onderbreking beschrijft (...when the ball hit Sarah).</li></ul></div>'},
{heading:'Grammar 4: can, could en should',html:'<div class=\'box\'><h4>Can, could en should</h4><p>Bij can, could en should voeg je <b>geen -s</b> toe na he, she of it.</p><div class=\'g3\'><div class=\'box\'><h4>can</h4><p>vaardigheden en toestemming: wat iemand kan of mag.</p></div><div class=\'box\'><h4>could</h4><p>wat zou kunnen gebeuren, of wat iemand vroeger kon/mocht. Ook een beleefde manier om toestemming te vragen.</p></div><div class=\'box\'><h4>should</h4><p>advies geven: wat iemand het beste kan doen.</p></div></div></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>You should rest.</td><td>Je zou moeten rusten.</td></tr><tr><td>Could I open the window?</td><td>Zou ik het raam open mogen doen?</td></tr><tr><td>She can run very fast.</td><td>Zij kan heel snel rennen.</td></tr></table></div><div class=\'call\'>Advies geven met should combineer je vaak met woorden als rest, take a break, cut down on, take it easy.</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Geen -s na can/could/should, ook niet bij he/she/it.</li><li>Can = kunnen/mogen nu, could = verleden of beleefd verzoek, should = advies.</li></ul></div>'},
{heading:'Praten over gezondheid',html:'<div class=\'box\'><h4>Advies geven en geruststellen</h4><p>Als een klasgenoot niet lekker is, kun je deze zinnen gebruiken.</p><ul class=\'lst\'><li>You look a bit pale. I think you need to see your doctor.</li><li>He examined me but couldn\'t find anything.</li><li>I spoke to Dr Haynes. She gave me some medicine for my allergy.</li><li>She said I should take these pills three times a day.</li></ul></div><div class=\'call\'>Combineer should met de tips-woorden uit dit hoofdstuk om iemand advies te geven, bijvoorbeeld: <i>You should rest and take it easy.</i></div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Gebruik should + tips-woorden om advies te geven.</li><li>Gebruik health conditions-woorden om te zeggen wat er mis is.</li></ul></div>'}
],
terms:[
['appointment','afspraak',0],
['crutches','krukken',0],
['dentist','tandarts',0],
['(to) examine','onderzoeken',0],
['(to) get better','beter worden',0],
['(to) hurt','pijn doen',0],
['plaster','pleister, gips',0],
['waiting room','wachtkamer',0],
['x-ray','röntgenfoto',0],
['(to) be ill','ziek zijn',0],
['(to) bleed','bloeden',0],
['(to) bump','stoten',0],
['(to) faint','flauwvallen',0],
['(to) feel sick','zich misselijk voelen',0],
['(to) throw up','overgeven',0],
['black eye','blauw oog',1],
['(to) feel dizzy','duizelig zijn',1],
['(to) feel miserable','zich ellendig voelen',1],
['(to) have a cold','verkouden zijn',1],
['(to) have a fever','koorts hebben',1],
['(to) have the flu','de griep hebben',1],
['headache','hoofdpijn',1],
['runny nose','loopneus',1],
['sore throat','keelpijn',1],
['toothache','kiespijn, tandpijn',1],
['(to) cure','genezen',1],
['(to) cut down on','verminderen',1],
['(to) heal','herstellen, genezen',1],
['(to) improve','verbeteren',1],
['(to) rest','rusten',1],
['(to) take a break','een pauze nemen',1],
['(to) take it easy','het rustig aan doen',1],
['(to) worry','zich zorgen maken',1],
['ankle','enkel',2],
['swollen','opgezwollen',2],
['pale','bleek',2],
['painful','pijnlijk',3],
['(to) explain','uitleggen',3],
['probably','waarschijnlijk',3],
['(to) encourage','aanmoedigen',4],
['(to) taste','proeven',4]
],
cards:[
['Wat betekent \'appointment\'?','afspraak',0],
['Wat betekent \'to examine\'?','onderzoeken',0],
['Wat is het Engelse woord voor \'wachtkamer\'?','waiting room',0],
['Wat betekent \'to faint\'?','flauwvallen',0],
['Wat betekent \'to throw up\'?','overgeven',0],
['Wat betekent \'headache\'?','hoofdpijn',1],
['Wat is het Engelse woord voor \'keelpijn\'?','sore throat',1],
['Wat betekent \'to have the flu\'?','de griep hebben',1],
['Wat betekent \'to take it easy\'?','het rustig aan doen',1],
['Hoe maak je de past continuous?','met was/were + werkwoord + -ing',2],
['Maak de past continuous van \'to wait\' bij \'they\'.','they were waiting',2],
['Voeg je een -s toe na \'she can\'?','nee, geen -s na can/could/should',3],
['Welk modaal werkwoord gebruik je om advies te geven?','should',3],
['Welk modaal werkwoord gebruik je voor een beleefd verzoek?','could',3],
['Noem een zin om iemand gerust te stellen die ziek is.','bijvoorbeeld: I think you need to see your doctor.',4]
],
quiz:[
['Wat betekent \'appointment\'?',['ziekte','afspraak','pleister','wachtkamer'],1,'Appointment betekent afspraak.'],
['Welk woord betekent \'onderzoeken\'?',['to examine','to hurt','to heal','to worry'],0,'To examine betekent onderzoeken.'],
['Wat betekent \'crutches\'?',['krukken','gips','röntgenfoto','tandarts'],0,'Crutches betekent krukken.'],
['Wat betekent \'to faint\'?',['hoesten','bloeden','flauwvallen','overgeven'],2,'To faint betekent flauwvallen.'],
['Welk woord betekent \'hoofdpijn\'?',['toothache','headache','sore throat','runny nose'],1,'Headache betekent hoofdpijn.'],
['Wat betekent \'to have a fever\'?',['verkouden zijn','koorts hebben','de griep hebben','duizelig zijn'],1,'To have a fever betekent koorts hebben.'],
['Wat betekent \'to cut down on\'?',['genezen','verminderen','verbeteren','volhouden'],1,'To cut down on betekent verminderen.'],
['Welk woord betekent \'zich zorgen maken\'?',['to worry','to rest','to improve','to heal'],0,'To worry betekent zich zorgen maken.'],
['Hoe maak je de past continuous van \'to work\'?',['worked','working','was/were working','did work'],2,'De past continuous maak je met was/were + werkwoord + -ing: was/were working.'],
['Welke zin is een correcte past continuous?',['I was wait for the bus.','I waiting for the bus.','I was waiting for the bus.','I were waiting for the bus.'],2,'Bij \'I\' gebruik je was: I was waiting for the bus.'],
['Welke zin is grammaticaal correct?',['They was working out.','They were working out.','They is working out.','They working out.'],1,'Bij they gebruik je were: They were working out.'],
['Wanneer gebruik je de past continuous vaak?',['voor een korte, afgesloten actie','voor een langere actie die onderbroken werd','voor een actie in de toekomst','voor een gewoonte in het heden'],1,'De past continuous beschrijft een langere actie die vaak onderbroken werd door iets anders.'],
['Welke zin gebruikt \'should\' correct om advies te geven?',['You shoulds rest.','You should to rest.','You should rest.','You should resting.'],2,'Na should gebruik je het hele werkwoord zonder -s of \'to\': You should rest.'],
['Welke zin gebruikt \'can\' correct?',['She can swims very well.','She can swim very well.','She cans swim very well.','She can to swim very well.'],1,'Na can gebruik je het hele werkwoord zonder -s: She can swim very well.'],
['Wat is het verschil tussen \'can\' en \'could\'?',['geen verschil','can is verleden tijd van could','could kan verleden tijd of een beleefd verzoek zijn','could is alleen voor toestemming'],2,'Could gebruik je voor het verleden of om iets beleefd te vragen.'],
['Wat betekent \'to rest\'?',['rusten','onderzoeken','verbeteren','volhouden'],0,'To rest betekent rusten.'],
['Wat betekent \'swollen\'?',['bleek','pijnlijk','opgezwollen','duizelig'],2,'Swollen betekent opgezwollen.'],
['Welke zin past bij het geven van advies aan een zieke klasgenoot?',['He examined me yesterday.','You should rest and take it easy.','They were working out.','I have a runny nose.'],1,'You should rest and take it easy is een voorbeeld van advies geven met should.']
]
});
