import { registerChapter } from '../../../registry.js';

registerChapter('engels|bbl|3|2', {
title:'Crime',
summary:[
{heading:'2.1 Committing a crime: Een misdaad begaan',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>Je leert praten over <b>misdaad</b>, over de <b>rechtszaal</b> en over <b>gevaarlijke situaties</b>. Bij de grammatica leer je de <b>modal verbs</b> en <b>adverbs of frequency</b>.</p></div><div class=\'box\' style=\'margin-top:0\'><h4>Theme words: Committing a crime</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>(to) chase</td><td>achtervolgen</td></tr><tr><td>crime scene</td><td>plaats delict</td></tr><tr><td>(to) escape</td><td>ontsnappen</td></tr><tr><td>handcuffs</td><td>handboeien</td></tr><tr><td>(to) investigate</td><td>onderzoeken</td></tr><tr><td>pickpocket</td><td>zakkenroller</td></tr><tr><td>robbery</td><td>beroving, overval</td></tr><tr><td>(to) scam</td><td>oplichten</td></tr><tr><td>(to) shoplift</td><td>winkeldiefstal plegen</td></tr><tr><td>(to) steal</td><td>stelen</td></tr><tr><td>theft</td><td>diefstal</td></tr></table></div><div class=\'call warn\' style=\'margin-bottom:0\'><b>Let op het verschil:</b> <i>theft</i> is de <b>daad</b> (diefstal), <i>thief</i> is de <b>persoon</b> (dief), en <i>(to) steal</i> is het <b>werkwoord</b> (stelen).</div></div><div class=\'box\' style=\'margin-top:1rem\'><h4>Iemand beschrijven</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>aggressive</td><td>agressief</td></tr><tr><td>birthmark</td><td>moedervlek</td></tr><tr><td>confused</td><td>verward</td></tr><tr><td>(to) damage</td><td>beschadigen</td></tr><tr><td>scar</td><td>litteken</td></tr><tr><td>suspicious</td><td>verdacht</td></tr><tr><td>violent</td><td>gewelddadig</td></tr></table></div></div><div class=\'call sum\'><b>Om te onthouden (2.1)</b><ul class=\'lst\'><li><b>Theft</b> = de daad, <b>thief</b> = de persoon, <b>(to) steal</b> = het werkwoord.</li><li><b>Crime scene</b> is de plaats delict.</li><li><b>Suspicious</b> = verdacht; <b>suspect</b> = de verdachte persoon.</li></ul></div>'},
{heading:'2.2 In court: In de rechtszaal',html:'<div class=\'box\'><h4>Theme words: Court</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>(to) be released</td><td>vrijgelaten worden</td></tr><tr><td>court</td><td>rechtbank</td></tr><tr><td>(to) fine</td><td>beboeten; boete</td></tr><tr><td>(i)llegal</td><td>(il)legaal</td></tr><tr><td>judge</td><td>rechter</td></tr><tr><td>lawyer</td><td>advocaat</td></tr><tr><td>proof</td><td>bewijs</td></tr><tr><td>punishment</td><td>straf</td></tr><tr><td>suspect</td><td>verdachte</td></tr><tr><td>witness</td><td>getuige</td></tr></table></div></div><div class=\'box\' style=\'margin-top:1rem\'><h4>Wie is wie in de rechtszaal?</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Persoon</th><th>Doet wat</th></tr><tr><td><b>Suspect</b></td><td>wordt beschuldigd van de misdaad</td></tr><tr><td><b>Lawyer</b></td><td>verdedigt de verdachte</td></tr><tr><td><b>Witness</b></td><td>heeft iets gezien en vertelt dat</td></tr><tr><td><b>Judge</b></td><td>bepaalt de straf</td></tr></table></div><div class=\'call\' style=\'margin-bottom:0\'><b>Voorbeeldstraffen:</b> <i>community service</i> (taakstraf), <i>a fine</i> (geldboete), <i>prison</i> (gevangenis).</div></div><div class=\'call sum\'><b>Om te onthouden (2.2)</b><ul class=\'lst\'><li><b>Judge</b> = rechter, <b>lawyer</b> = advocaat, <b>witness</b> = getuige.</li><li><b>Proof</b> = bewijs, <b>punishment</b> = straf.</li><li><b>(To) fine</b> kan werkwoord én zelfstandig naamwoord zijn: beboeten of een boete.</li></ul></div>'},
{heading:'2.3 Emergencies: Noodsituaties',html:'<div class=\'box\'><h4>Theme words: Emergencies</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>accident</td><td>ongeluk</td></tr><tr><td>(to) alert</td><td>waarschuwen, alarmeren</td></tr><tr><td>(to) deal with</td><td>omgaan met, aanpakken</td></tr><tr><td>emergency services</td><td>hulpdiensten</td></tr><tr><td>flammable</td><td>brandbaar</td></tr><tr><td>(to) get help</td><td>hulp halen</td></tr><tr><td>(to) keep calm</td><td>rustig blijven</td></tr><tr><td>(to) protect</td><td>beschermen</td></tr><tr><td>siren</td><td>sirene</td></tr><tr><td>(to) warn</td><td>waarschuwen</td></tr></table></div><div class=\'call warn\' style=\'margin-bottom:0\'><b>Twee woorden voor waarschuwen:</b> <i>(to) warn</i> is iemand vertellen dat er gevaar is. <i>(to) alert</i> is de hulpdiensten inschakelen. Ze lijken op elkaar maar zijn niet hetzelfde.</div></div><div class=\'box\' style=\'margin-top:1rem\'><h4>Zinnen bij een noodsituatie</h4><div class=\'term\'><b>Watch out for pickpockets.</b><span>Pas op voor zakkenrollers.</span></div><div class=\'term\'><b>You should stay calm.</b><span>Je moet rustig blijven.</span></div><div class=\'term\'><b>Make sure you lock the door.</b><span>Zorg dat je de deur op slot doet.</span></div><div class=\'term\' style=\'margin-bottom:0\'><b>You need to alert the emergency services.</b><span>Je moet de hulpdiensten waarschuwen.</span></div></div><div class=\'call sum\'><b>Om te onthouden (2.3)</b><ul class=\'lst\'><li><b>Emergency services</b> = hulpdiensten (politie, brandweer, ambulance).</li><li><b>(To) warn</b> = iemand waarschuwen. <b>(To) alert</b> = de hulpdiensten inschakelen.</li><li><b>Flammable</b> = brandbaar: belangrijk woord op waarschuwingsborden.</li></ul></div>'},
{heading:'2.4 Grammar: Modal verbs en adverbs of frequency',html:'<div class=\'box\'><h4>Modal verbs: hulpwerkwoorden</h4><p>Deze woorden zeggen iets over wat <b>kan</b>, <b>mag</b> of <b>moet</b>. Na een modal verb komt <b>altijd het hele werkwoord</b>: geen \'to\', geen -s.</p><div class=\'tblwrap\' style=\'margin-top:.7rem\'><table class=\'tbl\'><tr><th>Modal</th><th>Betekenis</th><th>Voorbeeld</th></tr><tr><td><b>can</b></td><td>kunnen, mogen</td><td>She <b>can</b> swim.</td></tr><tr><td><b>could</b></td><td>kon, zou kunnen</td><td>He <b>could</b> run fast.</td></tr><tr><td><b>may</b></td><td>mogen</td><td>You <b>may</b> leave now.</td></tr><tr><td><b>must</b></td><td>moeten (verplicht)</td><td>You <b>must</b> stop here.</td></tr><tr><td><b>should</b></td><td>zou moeten (advies)</td><td>You <b>should</b> stay calm.</td></tr><tr><td><b>will</b></td><td>zullen, gaan</td><td>I <b>will</b> help you.</td></tr></table></div></div><div class=\'box\' style=\'margin-top:1rem\'><h4>To be able to</h4><p><b>Can</b> heeft geen verleden tijd of toekomende tijd. Daarvoor gebruik je <b>to be able to</b> (in staat zijn om).</p><div class=\'tblwrap\' style=\'margin-top:.6rem\'><table class=\'tbl\'><tr><th>Tijd</th><th>Vorm</th></tr><tr><td>nu</td><td>I <b>can</b> swim / I <b>am able to</b> swim</td></tr><tr><td>verleden</td><td>I <b>was able to</b> swim</td></tr><tr><td>toekomst</td><td>I <b>will be able to</b> swim</td></tr></table></div><div class=\'call warn\' style=\'margin-bottom:0\'><i>I will can swim</i> bestaat niet. Twee modals achter elkaar mag nooit: daarom bestaat <b>to be able to</b>.</div></div><h5 class=\'sub\'>Adverbs of frequency: Hoe vaak?</h5><div class=\'box\'><p>Een <b>adverb of frequency</b> zegt hoe vaak iets gebeurt.</p><div class=\'tblwrap\' style=\'margin-top:.6rem\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th><th>Hoe vaak</th></tr><tr><td>always</td><td>altijd</td><td class=\'yes\'>100%</td></tr><tr><td>usually</td><td>meestal</td><td class=\'yes\'>±80%</td></tr><tr><td>often</td><td>vaak</td><td class=\'half\'>±60%</td></tr><tr><td>sometimes</td><td>soms</td><td class=\'half\'>±40%</td></tr><tr><td>never</td><td>nooit</td><td class=\'no\'>0%</td></tr></table></div><div class=\'call\' style=\'margin-top:.8rem;margin-bottom:0\'><b>De plaatsingsregel:</b> een adverb of frequency staat <b>vóór het hoofdwerkwoord</b>, maar <b>ná</b> een vorm van <i>be</i>.</div><ul class=\'lst\' style=\'margin-top:.8rem\'><li>Susan <b>always</b> takes the bus to school. <span class=\'dim\'>(vóór het werkwoord)</span></li><li>She <b>is always</b> on time. <span class=\'dim\'>(ná \'is\')</span></li><li>My brother <b>never</b> does his homework on time.</li></ul></div><div class=\'call sum\'><b>Om te onthouden (2.4)</b><ul class=\'lst\'><li>Na een <b>modal verb</b> komt het hele werkwoord: geen \'to\', geen -s.</li><li><b>Must</b> = verplicht. <b>Should</b> = advies.</li><li>Verleden of toekomst van \'can\' → <b>to be able to</b>.</li><li><b>Adverbs of frequency</b> staan vóór het hoofdwerkwoord, maar ná <i>be</i>.</li></ul></div>'}
],
terms:[
['(to) chase','achtervolgen',0],
['crime scene','plaats delict',0],
['(to) escape','ontsnappen',0],
['handcuffs','handboeien',0],
['(to) investigate','onderzoeken',0],
['pickpocket','zakkenroller',0],
['robbery','beroving, overval',0],
['(to) scam','oplichten',0],
['(to) shoplift','winkeldiefstal plegen',0],
['(to) steal','stelen',0],
['theft','diefstal',0],
['aggressive','agressief',0],
['birthmark','moedervlek',0],
['confused','verward',0],
['(to) damage','beschadigen',0],
['scar','litteken',0],
['suspicious','verdacht',0],
['violent','gewelddadig',0],
['(to) be released','vrijgelaten worden',1],
['court','rechtbank',1],
['(to) fine','beboeten; boete',1],
['(i)llegal','(il)legaal',1],
['judge','rechter',1],
['lawyer','advocaat',1],
['proof','bewijs',1],
['punishment','straf',1],
['suspect','verdachte',1],
['witness','getuige',1],
['accident','ongeluk',2],
['(to) alert','alarmeren',2],
['(to) deal with','omgaan met',2],
['emergency services','hulpdiensten',2],
['flammable','brandbaar',2],
['(to) get help','hulp halen',2],
['(to) keep calm','rustig blijven',2],
['(to) protect','beschermen',2],
['siren','sirene',2],
['(to) warn','waarschuwen',2],
['modal verb','hulpwerkwoord zoals can, must of should',3],
['to be able to','in staat zijn om: vervangt "can" in verleden en toekomst',3],
['adverb of frequency','bijwoord dat zegt hoe vaak iets gebeurt',3],
['always','altijd',3],
['usually','meestal',3],
['often','vaak',3],
['sometimes','soms',3],
['never','nooit',3]
],
cards:[
['(to) chase','achtervolgen',0],
['crime scene','plaats delict',0],
['(to) escape','ontsnappen',0],
['handcuffs','handboeien',0],
['(to) investigate','onderzoeken',0],
['pickpocket','zakkenroller',0],
['robbery','beroving, overval',0],
['(to) shoplift','winkeldiefstal plegen',0],
['theft','diefstal',0],
['scar','litteken',0],
['birthmark','moedervlek',0],
['suspicious','verdacht',0],
['violent','gewelddadig',0],
['Wat is het verschil tussen theft, thief en steal?','Theft = de daad, thief = de persoon, to steal = het werkwoord.',0],
['court','rechtbank',1],
['judge','rechter',1],
['lawyer','advocaat',1],
['witness','getuige',1],
['proof','bewijs',1],
['punishment','straf',1],
['suspect','verdachte',1],
['(to) be released','vrijgelaten worden',1],
['Wie bepaalt de straf in de rechtszaal?','The judge: de rechter.',1],
['Wie verdedigt de verdachte?','The lawyer: de advocaat.',1],
['accident','ongeluk',2],
['emergency services','hulpdiensten',2],
['flammable','brandbaar',2],
['siren','sirene',2],
['(to) warn','waarschuwen',2],
['(to) protect','beschermen',2],
['(to) keep calm','rustig blijven',2],
['Wat is het verschil tussen warn en alert?','Warn = iemand waarschuwen. Alert = de hulpdiensten inschakelen.',2],
['Wat komt er na een modal verb?','Het hele werkwoord: geen "to" en geen -s.',3],
['Wat is het verschil tussen must en should?','Must = verplicht. Should = advies.',3],
['Hoe zeg je "ik kon zwemmen" in het Engels?','I was able to swim (of: I could swim).',3],
['Waarom bestaat "to be able to"?','Omdat can geen verleden of toekomst heeft; twee modals achter elkaar mag niet.',3],
['always','altijd (100%)',3],
['usually','meestal',3],
['often','vaak',3],
['sometimes','soms',3],
['never','nooit',3],
['Waar staat een adverb of frequency?','Vóór het hoofdwerkwoord, maar ná een vorm van "be".',3],
['Susan ___ takes the bus. (always)','Susan always takes the bus.',3],
['She ___ on time. (always, met is)','She is always on time: ná "is".',3]
],
quiz:[
['What does "crime scene" mean?',['misdaadfilm','plaats delict','rechtszaal','politiebureau'],1,'Crime scene is de plaats delict: waar de misdaad gebeurde.'],
['What does "pickpocket" mean?',['zakdoek','zakkenroller','inbreker','pikhouweel'],1,'A pickpocket is een zakkenroller.'],
['What does "theft" mean?',['dief','diefstal','stelen','gestolen'],1,'Theft is de daad: diefstal. De persoon is a thief.'],
['What does "(to) investigate" mean?',['investeren','onderzoeken','uitvinden','achtervolgen'],1,'To investigate betekent onderzoeken. Let op: het lijkt op "investeren", maar dat is het niet.'],
['What does "scar" mean?',['schrik','litteken','moedervlek','wond'],1,'A scar is een litteken. A birthmark is een moedervlek.'],
['Who decides the punishment in court?',['The lawyer','The witness','The judge','The suspect'],2,'De judge (rechter) bepaalt de straf.'],
['What does "witness" mean?',['verdachte','getuige','advocaat','bewijs'],1,'A witness is een getuige: iemand die iets gezien heeft.'],
['What does "proof" mean?',['bewijs','proef','straf','beroep'],0,'Proof is bewijs. Let op: het lijkt op "proef", maar dat is het niet.'],
['What does "(to) be released" mean?',['veroordeeld worden','vrijgelaten worden','opgepakt worden','beboet worden'],1,'To be released betekent vrijgelaten worden.'],
['What does "flammable" mean?',['vlammend','brandbaar','onbrandbaar','gevaarlijk'],1,'Flammable betekent brandbaar: je ziet het op waarschuwingsborden.'],
['What does "emergency services" mean?',['noodgeval','hulpdiensten','nooduitgang','eerste hulp'],1,'Emergency services zijn de hulpdiensten: politie, brandweer en ambulance.'],
['What is the difference between "warn" and "alert"?',['Geen verschil','Warn = iemand waarschuwen, alert = hulpdiensten inschakelen','Warn = alarmeren, alert = beschermen','Warn is formeler'],1,'To warn is iemand waarschuwen, to alert is de hulpdiensten inschakelen.'],
['Which sentence is correct?',['You must to stop here.','You must stops here.','You must stop here.','You must stopping here.'],2,'Na een modal verb komt het hele werkwoord: must stop.'],
['What is the difference between "must" and "should"?',['Geen verschil','Must = verplicht, should = advies','Must = advies, should = verplicht','Must is beleefder'],1,'Must betekent verplicht, should geeft advies.'],
['How do you say "I could swim" in the future?',['I will can swim','I will could swim','I will be able to swim','I can will swim'],2,'Twee modals achter elkaar mag niet, dus: I will be able to swim.'],
['Which word means "meestal"?',['always','usually','sometimes','never'],1,'Usually betekent meestal, ongeveer 80% van de tijd.'],
['Where does an adverb of frequency go?',['Altijd achteraan','Vóór het hoofdwerkwoord','Altijd vooraan','Achter het lijdend voorwerp'],1,'Meestal vóór het hoofdwerkwoord, maar ná een vorm van "be".'],
['Which sentence is correct?',['Susan takes always the bus.','Susan always takes the bus.','Always Susan takes the bus.','Susan takes the bus always.'],1,'Het adverb staat vóór het hoofdwerkwoord: always takes.'],
['Which sentence is correct?',['She always is on time.','She is always on time.','Always she is on time.','She is on time always.'],1,'Na een vorm van "be" komt het adverb: is always.'],
['What does "suspicious" mean?',['verdachte (persoon)','verdacht','vermoeden','achterdocht'],1,'Suspicious betekent verdacht. De persoon is a suspect.']
]
});
