import { registerChapter } from '../../../registry.js';

registerChapter('engels|tl|3|2', {
title:'Crime',
summary:[
{heading:'Present perfect',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>Dit hoofdstuk gaat over <b>misdaad</b>: hoe je een misdaad aangeeft bij de politie, hoe je mensen waarschuwt in noodsituaties, en hoe een rechtszaak in zijn werk gaat (rechter, advocaat, vonnis).</p><p>Grammaticaal leer je de <i>present perfect</i> gebruiken voor gebeurtenissen die invloed hebben op nu, je maakt kennis met <i>onregelmatige werkwoorden</i>, en je leert modale werkwoorden zoals <i>can</i>, <i>could</i> en <i>to be able to</i> correct te gebruiken &ndash; inclusief hun ontkenningen.</p></div><div class=\'call\'>Mission van dit hoofdstuk: can, could en to be able to correct gebruiken; de present perfect en onregelmatige werkwoorden correct toepassen; een misdaad melden en mensen waarschuwen in noodsituaties.</div><div class=\'box\'><h4>Wanneer gebruik je de present perfect?</h4><p>Je gebruikt de <b>present perfect</b> (<i>have/has + past participle</i>):</p><ul class=\'lst\'><li>om te zeggen dat iets in het verleden is gebeurd en nu nog steeds belangrijk is (er is een link tussen verleden en heden)</li><li>om te praten over iets dat in het verleden is begonnen en nog steeds doorgaat</li><li>om te praten over ervaringen tot nu toe</li></ul><p>Bij signaalwoorden als <i>just</i>, <i>recently</i>, <i>already</i>, <i>yet</i> en <i>ever</i> gebruik je vaak de present perfect.</p></div><div class=\'voorbeeld\'><i>He <b>has</b> never <b>met</b> me.</i> &mdash; <i>I <b>have</b> never <b>been</b> there.</i> &mdash; <i>We <b>have travelled</b> there often.</i> &mdash; <i>A man <b>has just escaped</b> from the correctional facility.</i></div><div class=\'vergelijk\'><div><h5>past simple</h5><p>Een afgesloten gebeurtenis in het verleden, vaak met een tijdsaanduiding: <i>I <b>talked</b> to her this morning.</i></p></div><div><h5>present perfect</h5><p>Een gebeurtenis met gevolgen voor nu, of nog niet afgesloten: <i>I <b>have</b> just <b>reported</b> the theft.</i></p></div></div><div class=\'call warn\'><b>Veelgemaakte fout:</b> Een regelmatig werkwoord krijgt in de past participle net als in de past simple een <i>-ed</i>: <i>to report &rarr; reported &rarr; reported</i>. Verwar dit niet met onregelmatige werkwoorden zoals <i>to go</i>.</div>'},
{heading:'Onregelmatige werkwoorden',html:'<div class=\'box\'><h4>Irregular verbs</h4><p>Onregelmatige werkwoorden hebben drie verschillende vormen: de <b>infinitief</b> (hele werkwoord), de <b>past simple</b> en de <b>past participle</b>. Deze vormen moet je uit je hoofd leren, want ze volgen geen vaste regel.</p></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>infinitief</th><th>past simple</th><th>past participle</th></tr><tr><td>to go</td><td>went</td><td>gone</td></tr><tr><td>to think</td><td>thought</td><td>thought</td></tr><tr><td>to drive</td><td>drove</td><td>driven</td></tr><tr><td>to steal</td><td>stole</td><td>stolen</td></tr><tr><td>to catch</td><td>caught</td><td>caught</td></tr><tr><td>to see</td><td>saw</td><td>seen</td></tr></table></div><div class=\'call\'>Een compleet overzicht van alle onregelmatige werkwoorden staat achter in het boek, in de Grammar Survey. Leer er per week een paar uit je hoofd.</div><div class=\'check\' onclick=\'toonCheck(this)\'><p><b>Check:</b> Wat is de past participle van \'to steal\'?</p><p class=\'antwoord\'>stolen &ndash; bijvoorbeeld: \'Someone has stolen my bike.\'</p></div>'},
{heading:'Modale werkwoorden',html:'<div class=\'box\'><h4>Can, could en to be able to</h4><p>Modale werkwoorden (zoals <i>can</i>, <i>could</i>, <i>should</i>, <i>must</i> en <i>to have to</i>) zijn een speciaal soort werkwoord. Ze worden altijd gevolgd door een infinitief zonder \'to\'.</p><ul class=\'lst\'><li><b>can</b>: verzoeken doen, toestemming vragen/geven en praten over mogelijkheden en vaardigheden</li><li><b>to be able to</b>: alleen om te praten over iemands mogelijkheden of vaardigheden</li><li><b>could</b>: de verleden tijd van can; ook om beleefder of formeler een vraag te stellen, of om te praten over een mogelijkheid in de toekomst</li></ul></div><div class=\'voorbeeld\'><i>Could you lend me your phone, please?</i> (beleefd verzoek) &mdash; <i>I wasn\'t <b>able to</b> come to the party.</i> (vaardigheid/mogelijkheid in het verleden)</div><div class=\'box\'><h4>Ontkenningen van modale werkwoorden</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>bevestigend</th><th>ontkennend</th><th>betekenis</th></tr><tr><td>can</td><td>cannot / can\'t</td><td>vaardigheden en mogelijkheden</td></tr><tr><td>could</td><td>could not / couldn\'t</td><td>mogelijkheid in de toekomst, beleefde vraag, verleden tijd van can</td></tr><tr><td>should</td><td>should not / shouldn\'t</td><td>advies</td></tr><tr><td>must</td><td>must not / mustn\'t</td><td>verplichting van de spreker</td></tr><tr><td>to be able to</td><td>am not / isn\'t / wasn\'t able to</td><td>vaardigheden en mogelijkheden</td></tr><tr><td>to have to</td><td>don\'t / doesn\'t / didn\'t have to</td><td>verplichting van iemand anders</td></tr></table></div></div><div class=\'call warn\'><b>Veelgemaakte fout:</b> <i>must not</i> en <i>don\'t have to</i> betekenen <b>niet</b> hetzelfde! <i>must not</i> gebruik je als iets niet mag (verboden); <i>don\'t have to</i> gebruik je als iets niet verplicht is (maar wel mag).</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Modale werkwoorden worden gevolgd door een infinitief zonder \'to\'.</li><li>Om een modaal werkwoord te ontkennen, voeg je \'not\' of \'-n\'t\' toe.</li><li>Uitzondering: \'to have to\' ontken je met een vorm van \'to do\' (don\'t/doesn\'t/didn\'t have to).</li></ul></div>'},
{heading:'Een misdaad melden',html:'<div class=\'box\'><h4>Stone: reporting a crime</h4><p>Met deze vaste zinnen kun je bij de politie een misdaad melden of aangifte doen.</p></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>I\'d like to report...</td><td>Ik wil graag ... aangeven.</td></tr><tr><td>He has stolen...</td><td>Hij heeft ... gestolen.</td></tr><tr><td>Someone has taken...</td><td>Iemand heeft ... meegenomen.</td></tr><tr><td>Could you describe... what he looked like?</td><td>Kun je beschrijven hoe hij eruitzag?</td></tr><tr><td>Can you tell me what happened?</td><td>Kun je vertellen wat er gebeurd is?</td></tr><tr><td>Has the suspect...?</td><td>Heeft de verdachte...?</td></tr><tr><td>Has the thief escaped?</td><td>Is de dief ontsnapt?</td></tr><tr><td>Someone scammed the victim.</td><td>Iemand lichtte het slachtoffer op.</td></tr><tr><td>Someone harassed me online.</td><td>Iemand viel me online lastig.</td></tr></table></div><div class=\'box\'><h4>Theme words &ndash; delicten</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>burglary</td><td>inbraak</td></tr><tr><td>crime scene</td><td>plaats delict</td></tr><tr><td>handcuffs</td><td>handboeien</td></tr><tr><td>intruder</td><td>indringer</td></tr><tr><td>robbery</td><td>beroving / overval</td></tr><tr><td>vandalism</td><td>vandalisme</td></tr><tr><td>to break in</td><td>inbreken</td></tr><tr><td>to chase</td><td>achtervolgen</td></tr><tr><td>to escape</td><td>ontsnappen</td></tr><tr><td>to investigate</td><td>onderzoeken</td></tr><tr><td>to pickpocket</td><td>zakkenrollen</td></tr><tr><td>to shoplift</td><td>winkeldiefstal plegen</td></tr></table></div></div><div class=\'box\'><h4>Theme words &ndash; recht en rechtspraak</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>illegal</td><td>illegaal</td></tr><tr><td>judge</td><td>rechter</td></tr><tr><td>lawyer</td><td>advocaat</td></tr><tr><td>proof</td><td>bewijs</td></tr><tr><td>punishment</td><td>straf</td></tr><tr><td>sentence</td><td>vonnis</td></tr><tr><td>trial</td><td>rechtszaak</td></tr><tr><td>verdict</td><td>uitspraak</td></tr><tr><td>to be charged with</td><td>beschuldigd worden van</td></tr><tr><td>to be released</td><td>vrijgelaten worden</td></tr><tr><td>to fine</td><td>beboeten</td></tr><tr><td>to testify</td><td>getuigen</td></tr></table></div></div>'},
{heading:'Mensen waarschuwen',html:'<div class=\'box\'><h4>Stone: warning people</h4><p>In een noodsituatie is het belangrijk dat je mensen snel en duidelijk kunt waarschuwen.</p></div><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>When you\'re in an emergency,...</td><td>Als je in nood bent,...</td></tr><tr><td>If there is..., don\'t panic.</td><td>Als er ... is, raak dan niet in paniek.</td></tr><tr><td>You have to notify the police.</td><td>Je moet de politie inlichten.</td></tr><tr><td>Always clear the way for...</td><td>Maak altijd ruimte voor...</td></tr><tr><td>Watch out for... when you visit...</td><td>Kijk uit voor ... als je ... bezoekt.</td></tr><tr><td>Beware of...</td><td>Pas op voor...</td></tr><tr><td>You must change your password...</td><td>Je moet je wachtwoord ... veranderen.</td></tr><tr><td>Make sure to update your software...</td><td>Zorg dat je je software ... update.</td></tr><tr><td>This website..., but I could be wrong.</td><td>Deze website ..., maar ik kan het mis hebben.</td></tr><tr><td>I wouldn\'t be surprised if..., but you never know.</td><td>Het zou me niet verbazen als ..., maar je weet het nooit.</td></tr><tr><td>You cannot cycle...</td><td>Je mag niet fietsen...</td></tr><tr><td>You\'d better not park...</td><td>Je kunt maar beter niet parkeren...</td></tr></table></div><div class=\'box\'><h4>Theme words &ndash; noodsituaties en veiligheid</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>emergency services</td><td>hulpdiensten</td></tr><tr><td>mugger</td><td>straatrover</td></tr><tr><td>onlooker</td><td>omstander</td></tr><tr><td>paramedics</td><td>ambulancepersoneel</td></tr><tr><td>premises</td><td>terrein / pand</td></tr><tr><td>restricted</td><td>verboden toegang / beperkt</td></tr><tr><td>to alert</td><td>waarschuwen</td></tr><tr><td>to evacuate</td><td>evacueren</td></tr><tr><td>to notify</td><td>in kennis stellen</td></tr><tr><td>to protect</td><td>beschermen</td></tr><tr><td>to secure</td><td>beveiligen</td></tr><tr><td>to threaten</td><td>bedreigen</td></tr></table></div></div><div class=\'diagram-nodig\'>Stroomschema: wat doe je bij een noodgeval? (1. blijf kalm &rarr; 2. bel de hulpdiensten &rarr; 3. maak ruimte voor hulpverleners &rarr; 4. volg instructies op)</div>'},
{heading:'Misdadigers en gedrag beschrijven',html:'<div class=\'box\'><h4>Een verdachte beschrijven</h4><p>Als je getuige bent van een misdrijf, is het belangrijk dat je iemands uiterlijk en gedrag goed kunt beschrijven.</p></div><div class=\'box\'><h4>Theme words &ndash; gedrag beschrijven</h4><div class=\'tblwrap\'><table class=\'tbl\'><tr><th>Engels</th><th>Nederlands</th></tr><tr><td>aggressive</td><td>agressief</td></tr><tr><td>armed</td><td>gewapend</td></tr><tr><td>birthmark</td><td>moedervlek</td></tr><tr><td>confused</td><td>verward</td></tr><tr><td>deliberately</td><td>opzettelijk</td></tr><tr><td>on purpose</td><td>expres</td></tr><tr><td>shabby</td><td>sjofel</td></tr><tr><td>suspicious</td><td>verdacht</td></tr><tr><td>to damage</td><td>beschadigen</td></tr><tr><td>to harass</td><td>lastigvallen</td></tr><tr><td>to scam</td><td>oplichten</td></tr><tr><td>to steal</td><td>stelen</td></tr></table></div></div><div class=\'call\'>Gebruik deze woorden samen met de present perfect om te melden wat je hebt gezien: <i>I have noticed a suspicious man. He was armed and he has damaged a car.</i></div><div class=\'call warn\'><b>Veelgemaakte fout:</b> \'on purpose\' en \'deliberately\' betekenen allebei \'expres/opzettelijk\' &ndash; verwar dit niet met \'suspicious\' (verdacht), dat gaat over hoe iets/iemand overkomt, niet over intentie.</div>'}
],
terms:[
['present perfect','have/has + past participle; iets uit het verleden dat relevant is voor nu',0],
['just / already / yet','signaalwoorden die vaak samen met de present perfect gebruikt worden',0],
['past participle','het voltooid deelwoord, gebruikt in de present perfect (bijv. gone, stolen)',1],
['to steal - stole - stolen','onregelmatig werkwoord: stelen',1],
['to be able to','in staat zijn om iets te doen',2],
['mustn\'t','iets is verboden (mag niet)',2],
['don\'t have to','iets is niet verplicht (maar mag wel)',2],
['burglary','inbraak',3],
['to shoplift','winkeldiefstal plegen',3],
['verdict','uitspraak van de rechter',3],
['lawyer','advocaat',3],
['to notify','in kennis stellen / waarschuwen',4],
['emergency services','hulpdiensten',4],
['to evacuate','evacueren',4],
['restricted','verboden toegang / beperkt',4],
['suspicious','verdacht',5],
['armed','gewapend',5],
['deliberately','opzettelijk',5],
['to harass','lastigvallen',5]
],
cards:[
['Wanneer gebruik je de present perfect?','Als iets in het verleden is gebeurd maar nog relevant is voor nu, of nog doorgaat',0],
['Hoe vorm je de present perfect?','have/has + past participle',0],
['Wat is de past simple van \'to go\'?','went',1],
['Wat is de past participle van \'to drive\'?','driven',1],
['Waarvoor gebruik je \'to be able to\' in tegenstelling tot \'can\'?','Alleen om te praten over iemands mogelijkheden of vaardigheden',2],
['Wat is het verschil tussen \'mustn\'t\' en \'don\'t have to\'?','\'mustn\'t\' = verboden, \'don\'t have to\' = niet verplicht (maar mag wel)',2],
['Hoe zeg je in het Engels \'Ik wil graag ... aangeven\'?','I\'d like to report...',3],
['Wat betekent \'to pickpocket\'?','zakkenrollen',3],
['Wat betekent \'verdict\'?','uitspraak van de rechter',3],
['Hoe zeg je \'Je moet de politie inlichten\' in het Engels?','You have to notify the police.',4],
['Wat betekent \'paramedics\'?','ambulancepersoneel',4],
['Wat betekent \'shabby\'?','sjofel',5]
],
quiz:[
['Welke zin staat in de present perfect?',['I talked to her this morning.','I have just reported the theft.','I am reporting the theft.','I will report the theft.'],1,'\'I have just reported the theft\' gebruikt have + past participle: de present perfect.'],
['Welk signaalwoord hoort vaak bij de present perfect?',['yesterday','last week','already','ago'],2,'\'already\' is een typisch signaalwoord voor de present perfect.'],
['Wat is de past participle van \'to steal\'?',['stealed','stole','stolen','stealt'],2,'\'to steal\' is onregelmatig: steal - stole - stolen.'],
['Wat is de past simple van \'to catch\'?',['catched','caught','catch','caughted'],1,'\'to catch\' is onregelmatig: catch - caught - caught.'],
['Welke zin gebruikt \'to be able to\' correct?',['I wasn\'t able to come to the party.','I not able to come to the party.','I couldn\'t able to come.','I am able came to the party.'],0,'\'to be able to\' vervoeg je met een vorm van \'to be\': \'I wasn\'t able to come to the party.\''],
['Wat betekent \'mustn\'t\' in \'You mustn\'t park here\'?',['het is niet verplicht','het is verboden','het is aan te raden','het is mogelijk'],1,'\'mustn\'t\' betekent dat iets verboden is.'],
['Wat betekent \'don\'t have to\' in \'You don\'t have to come\'?',['het is verboden','het is niet verplicht, maar mag wel','het is onmogelijk','het is aan te raden'],1,'\'don\'t have to\' geeft aan dat iets niet verplicht is, maar wel mag.'],
['Welke zin gebruik je om aangifte te doen van diefstal?',['Watch out for pickpockets.','I\'d like to report a theft.','You have to notify the police.','Beware of the dog.'],1,'\'I\'d like to report a theft\' is de juiste zin om aangifte te doen.'],
['Wat betekent \'burglary\'?',['overval','inbraak','vandalisme','zakkenrollerij'],1,'\'Burglary\' betekent inbraak.'],
['Wie spreekt in een rechtszaak het vonnis uit?',['the lawyer','the witness','the judge','the suspect'],2,'\'The judge\' (de rechter) spreekt het vonnis (sentence/verdict) uit.'],
['Welke zin gebruik je om mensen te waarschuwen in een noodsituatie?',['I\'d like to report a crime.','If there is a fire, don\'t panic.','Has the suspect escaped?','Someone has taken my bag.'],1,'\'If there is a fire, don\'t panic\' is een waarschuwing voor een noodsituatie.'],
['Wat betekent \'to evacuate\'?',['evacueren','arresteren','beschermen','onderzoeken'],0,'\'To evacuate\' betekent evacueren, dus mensen ergens vandaan halen wegens gevaar.'],
['Wat betekent \'restricted\' zoals in \'restricted area\'?',['besmet gebied','verboden toegang / beperkt gebied','beveiligd met camera\'s','verlaten gebied'],1,'\'Restricted\' betekent \'beperkt\' of \'verboden toegang\'.'],
['Welk woord past bij: \'The man looked ___ , so we called the police.\'',['suspicious','polite','loyal','optimistic'],0,'\'Suspicious\' (verdacht) past hier het beste.'],
['Wat betekent \'deliberately\'?',['per ongeluk','opzettelijk','voorzichtig','snel'],1,'\'Deliberately\' betekent opzettelijk / met opzet.'],
['Wat betekent \'to harass someone\'?',['iemand helpen','iemand lastigvallen','iemand arresteren','iemand ondervragen'],1,'\'To harass someone\' betekent iemand lastigvallen.'],
['Kies de correcte zin met een onregelmatig werkwoord: \'Someone has ___ my bike.\'',['steal','stealed','stole','stolen'],3,'Na \'has\' (present perfect) volgt de past participle: \'stolen\'.']
]
});
