import { registerChapter } from '../../../registry.js';

registerChapter('nederlands|bbl|4|3', {
title:'Fictie',
summary:[
{heading:'En toen...',html:'<div class=\'box\'><h4>Waar gaat dit hoofdstuk over?</h4><p>In dit hoofdstuk lees je fragmenten uit verhalen en leer je hoe schrijvers hun verhaal opbouwen: de volgorde van gebeurtenissen, de personages en gedichten. Aan het eind pas je dit toe door zelf een kort stukje fictie te schrijven.</p></div><div class=\'box\'><h4>Vertelvolgorde</h4><p>De gebeurtenissen in een verhaal worden in een bepaalde volgorde verteld. Dit heet de <b>vertelvolgorde</b>. Worden de gebeurtenissen verteld in de volgorde waarin ze gebeurd zijn? Dan noem je dat <b>chronologisch</b>. De auteur kan er ook voor kiezen de gebeurtenissen in een andere volgorde te vertellen.</p></div><div class=\'g2\'><div class=\'box\'><h4>Vertelheden</h4><p>Het \'nu\' van het verhaal noem je het vertelheden.</p></div><div class=\'box\'><h4>Flashback</h4><p>Onderbreekt de auteur het vertelheden om een eerdere gebeurtenis te beschrijven? Dan noem je dat een flashback. Zo maakt de auteur je nieuwsgierig of geeft hij extra informatie.</p></div></div><div class=\'call\'>Je herkent een flashback soms aan de lay-out van een tekst, bijvoorbeeld door een witregel of schuingedrukte tekst.</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Chronologisch = gebeurtenissen in de volgorde waarin ze gebeurden</li><li>Een flashback onderbreekt het vertelheden om iets uit het verleden te laten zien</li></ul></div>'},
{heading:'Fictie en ik',html:'<div class=\'box\'><h4>Jezelf herkennen in een verhaal</h4><p>Als lezer kun je jezelf soms herkennen in een personage of in een gebeurtenis uit een verhaal. Dat gebeurt vooral wanneer een schrijver gedachten, gevoelens en ervaringen herkenbaar beschrijft, ook al is het verhaal zelf verzonnen (fictie).</p></div><div class=\'call\'>Fictie hoeft niet \'echt gebeurd\' te zijn om herkenbaar te voelen: het gaat om de gevoelens en situaties die je zelf ook kent.</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Je kunt jezelf herkennen in fictieve personages en gebeurtenissen</li><li>Een verhaal hoeft niet echt gebeurd te zijn om herkenbaar te voelen</li></ul></div>'},
{heading:'Personages',html:'<div class=\'box\'><h4>Denken, voelen en handelen</h4><p>Een schrijver laat je een personage leren kennen door te beschrijven wat het personage <b>denkt</b>, <b>voelt</b> en <b>doet</b> (handelt). Ook situaties en verwikkelingen (problemen of ontwikkelingen in het verhaal) laten zien wie een personage is.</p></div><div class=\'box\'><h4>Spanning opbouwen</h4><p>Schrijvers gebruiken spanningstechnieken om een verhaal boeiender te maken, bijvoorbeeld door de lezer meer te laten weten dan het personage, door een dreigend gevaar aan te kondigen of door een cliffhanger aan het eind van een hoofdstuk.</p></div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Personages leer je kennen via hun denken, voelen en handelen</li><li>Spanningstechnieken houden de lezer geboeid</li></ul></div>'},
{heading:'Over gedichten',html:'<div class=\'box\'><h4>Vaste en vrije vorm</h4><p>Gedichten kunnen een <b>vaste vorm</b> hebben (met een vast rijmschema en aantal regels, zoals een sonnet) of een <b>vrije vorm</b> (zonder vaste regels voor rijm of regellengte).</p></div><div class=\'box\'><h4>Beeldspraak</h4><p><b>Beeldspraak</b> is figuurlijk taalgebruik: je bedoelt iets anders dan wat er letterlijk staat. Dichters gebruiken beeldspraak om gevoelens of beelden krachtiger over te brengen.</p></div><div class=\'call\'>Vriendschap is een populair onderwerp voor dichters, omdat het herkenbare gevoelens oproept bij veel lezers.</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Een gedicht kan een vaste of een vrije vorm hebben</li><li>Beeldspraak is figuurlijk taalgebruik</li></ul></div>'},
{heading:'Zelfschrijven',html:'<div class=\'box\'><h4>Je eigen kort verhaal</h4><p>Aan het einde van deze cursus pas je alles wat je hebt geleerd over fictie zelf toe: je schrijft een kort verhaal waarin je een duidelijke vertelvolgorde gebruikt, een personage laat denken, voelen en handelen, en eventueel spanningstechnieken toepast.</p></div><div class=\'call\'>Wissel je verhaal uit met een klasgenoot en geef elkaar constructieve feedback aan de hand van voorbeelden uit de tekst.</div><div class=\'call sum\'><b>Om te onthouden</b><ul class=\'lst\'><li>Gebruik vertelvolgorde, personages en eventueel spanningstechnieken in je eigen verhaal</li><li>Feedback geven doe je met concrete voorbeelden uit de tekst</li></ul></div>'}
],
terms:[
['Vertelvolgorde','De volgorde waarin de gebeurtenissen in een verhaal verteld worden.',0],
['Chronologisch','Gebeurtenissen worden verteld in de volgorde waarin ze echt gebeurd zijn.',0],
['Vertelheden','Het \'nu\' van het verhaal.',0],
['Flashback','Een onderbreking van het vertelheden om een eerdere gebeurtenis te beschrijven.',0],
['Fictie','Een verzonnen verhaal, in tegenstelling tot non-fictie dat echt gebeurd is.',1],
['Herkenbaarheid','De mate waarin een lezer zichzelf herkent in een verhaal of personage.',1],
['Personage','Een figuur (persoon) in een verhaal.',2],
['Verwikkeling','Een probleem of ontwikkeling in het verhaal waar het personage mee te maken krijgt.',2],
['Spanningstechniek','Een manier waarop een schrijver spanning opbouwt in een verhaal.',2],
['Vaste vorm (gedicht)','Een gedicht met een vast rijmschema en/of vast aantal regels.',3],
['Vrije vorm (gedicht)','Een gedicht zonder vaste regels voor rijm of regellengte.',3],
['Beeldspraak','Figuurlijk taalgebruik waarbij je iets anders bedoelt dan er letterlijk staat.',3]
],
cards:[
['Wat is chronologisch vertellen?','Gebeurtenissen vertellen in de volgorde waarin ze echt gebeurd zijn.',0],
['Wat is een flashback?','Een onderbreking van het vertelheden om een eerdere gebeurtenis te beschrijven.',0],
['Waaraan kun je een flashback soms herkennen in de lay-out?','Aan een witregel of schuingedrukte tekst.',0],
['Moet een verhaal echt gebeurd zijn om herkenbaar te voelen?','Nee, ook fictie kan herkenbare gevoelens en situaties bevatten.',1],
['Waardoor leer je een personage kennen?','Door te lezen wat het personage denkt, voelt en doet.',2],
['Wat is een verwikkeling?','Een probleem of ontwikkeling waar het personage mee te maken krijgt.',2],
['Wat is een vaste vorm bij een gedicht?','Een gedicht met een vast rijmschema en/of vast aantal regels.',3],
['Wat is beeldspraak?','Figuurlijk taalgebruik waarbij je iets anders bedoelt dan er letterlijk staat.',3],
['Wat oefen je bij Zelfschrijven?','Het zelf schrijven van een kort verhaal met vertelvolgorde en personages.',4],
['Hoe geef je goede feedback op een geschreven verhaal?','Constructief en met concrete voorbeelden uit de tekst.',4]
],
quiz:[
['Wat betekent \'chronologisch vertellen\'?',['Gebeurtenissen door elkaar vertellen','Gebeurtenissen vertellen in de volgorde waarin ze gebeurden','Alleen het einde van het verhaal vertellen','Een verhaal zonder personages vertellen'],1,'Chronologisch betekent dat de gebeurtenissen in de volgorde staan waarin ze echt plaatsvonden.'],
['Wat is een flashback?',['Een gedicht met een vaste vorm','Een onderbreking van het vertelheden om iets uit het verleden te laten zien','Een personage dat de hoofdrol speelt','Een tekstverband bij instructieve teksten'],1,'Een flashback onderbreekt het \'nu\' van het verhaal (vertelheden) om een eerdere gebeurtenis te tonen.'],
['Kan een verhaal herkenbaar voelen, ook al is het verzonnen?',['Nee, alleen echt gebeurde verhalen voelen herkenbaar','Ja, door herkenbare gevoelens en situaties','Nee, fictie is per definitie onherkenbaar','Alleen als het verhaal over dieren gaat'],1,'Fictie kan herkenbaar voelen doordat de gevoelens en situaties die beschreven worden ook bij de lezer passen.'],
['Waardoor leer je een personage het best kennen?',['Alleen door de titel van het boek','Door wat het personage denkt, voelt en doet','Door de kleur van de boekomslag','Door het aantal hoofdstukken'],1,'Denken, voelen en handelen van een personage laten zien wie het personage werkelijk is.'],
['Wat is een verwikkeling in een verhaal?',['Een gedicht in vrije vorm','Een probleem of ontwikkeling waar het personage mee te maken krijgt','Een tekstsoort zoals een recept','Een vertelvolgorde'],1,'Een verwikkeling is een probleem of ontwikkeling in het verhaal die het personage moet doorstaan.'],
['Wat is het verschil tussen een vaste en een vrije vorm bij gedichten?',['Een vaste vorm heeft geregeld rijm en regels, een vrije vorm niet','Een vrije vorm is altijd langer','Een vaste vorm gaat altijd over vriendschap','Er is geen verschil'],0,'Een vaste vorm heeft een vast rijmschema en/of aantal regels; een vrije vorm heeft die vaste regels niet.'],
['Wat is beeldspraak?',['Letterlijk taalgebruik','Figuurlijk taalgebruik waarbij je iets anders bedoelt dan er staat','Een ander woord voor tekstdoel','Een vorm van vertelvolgorde'],1,'Beeldspraak is figuurlijk taalgebruik: de woorden betekenen iets anders dan wat er letterlijk staat.'],
['Waarom is vriendschap een populair onderwerp voor dichters?',['Omdat het altijd rijmt','Omdat het herkenbare gevoelens oproept bij veel lezers','Omdat het een instructieve tekst is','Omdat het altijd in de vrije vorm geschreven wordt'],1,'Vriendschap roept bij veel lezers herkenbare gevoelens op, wat het een populair onderwerp maakt.'],
['Wat oefen je in de paragraaf Zelfschrijven?',['Het lezen van gedichten','Het schrijven van een eigen kort verhaal','Het maken van een mindmap','Het schrijven van een zakelijke e-mail'],1,'Bij Zelfschrijven pas je wat je geleerd hebt toe door zelf een kort verhaal te schrijven.'],
['Hoe geef je het best feedback op andermans verhaal?',['Alleen zeggen of je het goed of slecht vond','Constructief, met concrete voorbeelden uit de tekst','Nooit iets zeggen over verbeterpunten','Alleen over de spelling'],1,'Goede feedback is constructief en onderbouwd met concrete voorbeelden uit de tekst.']
]
});
